Feature/backend get count url words
nimblehq/ic-nextjs-prabesh-dahal pull request #101
Opened 2023-09-04 09:04 UTC by Prabeshpd

- Close #

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-09-05 10:30 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +    await this.buildUrlWithWordFilterQueryParams();
We can rearrange the build functions so that it build the `this.filterQuery` first, `this.paginationQuery` later

```suggestion
    this.buildUserQueryParams();
    this.buildKeywordQueryParams();
    this.buildUrlToFilterQueryParams();
    await this.buildUrlWithWordFilterQueryParams();
    this.buildPaginationQueryParams();
```

2023-09-05 10:37 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +    };
There is another filter that also sets the id property in filter. So, I am making sure that the existing ids don't get override and combining both array of ids.

2023-09-05 10:45 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +    };
Ah yes I just saw [that](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/102/files#diff-9649ebec8ad27f7ce281f313ccbda1b813badaffaa600c0a3388722e6e76060eR102) too. We can put this into the later PRs 🙈 

But as I see, the `buildUrlContainsAtLeastSpecificCharactersQueryParams` is executed after `buildUrlWithWordFilterQueryParams`. So do we need to worry about the override here? Should we only check the override in the `buildUrlContainsAtLeastSpecificCharactersQueryParams`?

2023-09-06 03:39 UTC, tednguyendev commented on test/queries/searchResultQuery.test.ts
> +    describe('given valid param for filter ad words url containing word', () => {
```suggestion
    describe('given there is filterAdUrlWord filter, () => {
```

2023-09-06 03:39 UTC, tednguyendev commented on test/queries/searchResultQuery.test.ts
> +    describe('there is NO filter ad words url param', () => {
```suggestion
    describe('given there is NO filterAdUrlWord filter', () => {
```

2023-09-06 03:52 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +    if (!this.filters?.filterAdUrlWord) return;
The name `filterAdUrlWord` sounds duplicated(the `filter` repeat twice, `filters?.filterAdUrlWord`), along with [other filters](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/102/files#diff-a19c21310c5cc89a48f322e52cc9e56d4307d265323e76416f6f1c2ee43ef2cbR5-R6).

How about just giving this the name `wordToSearch` like how you are doing in [the line under this](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/101/files#diff-9649ebec8ad27f7ce281f313ccbda1b813badaffaa600c0a3388722e6e76060eR68)?

2023-09-07 03:52 UTC, olivierobert commented on src/types/query.ts
> +  wordToSearch?: string | null;
Since the search is either on the keyword or URL there could be only two params. In terms of UX, a users can either do:

- keyword = "test" (exact or partial match)
- URL = "google" (partial match), "www.google.com" (exact match)

2023-09-07 03:52 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +    const searchResults = await this.databaseModel.findMany({ where: { userId: this.userId } });
Having to do a query before the main query is not ideal. Technically that should be done as a subquery. Did you consider using raw queries: https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access?

2023-09-07 03:56 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +    const searchResults = await this.databaseModel.findMany({ where: { userId: this.userId } });
Yes, I did consider using raw queries. Upon discussing with developers everyone suggested to not to go with raw query. So, went with this approach.

2023-09-08 03:26 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +            nonAdUrls: {
That is covered in previous PR that is merged. Since, there was code structure change had to change it too. 🙂

2023-09-08 03:26 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +       AND array_to_string(sr.ad_word_top_urls, ', ') ~ ${text}
Oh. It seems I have interchanged pattern and partial. Will update it. Thank you

2023-09-08 03:39 UTC, olivierobert commented on src/components/SearchResultList/SearchResultList.tsx
> +      const data = await listSearchResultsAction(paginationParams, { keyword });
We missed that variable naming but usually avoid using `data`:

```suggestion
      const fetchedSearchResult = await listSearchResultsAction(paginationParams, { keyword });
```

2023-09-08 03:39 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +    switch (searchType) {
I do not see a valid reason why the search type would apply to only to matching URLs. In terms of UX, I would expect that the search type would apply to both: I want to match the exact keyword or the exact URL at the same time.

2023-09-08 03:39 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +      where: { userId: this.userId, keyword: { contains: keyword ?? '' } },
The fallback to an empty string seems redundant if  `filterByKeyword` was only called if `keyword` was not null.

2023-09-08 03:39 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +    if (!this.filters.url?.text) {
This is quite expected because on the previous line we check for the value of the keyword and then the conditional is for checking if the value of the URL is set 🤔

2023-09-08 03:46 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +    switch (searchType) {
Since, keyword and url are different terms. I was planning to implement two different search for it. User may wants to search only the keywords without searching for the URLs. I was thinking since those two are separate concerns it would make sense to treat them differently. However, I have applied AND filter with keyword and filter params.

2023-09-08 03:47 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +      where: { userId: this.userId, keyword: { contains: keyword ?? '' } },
Empty string are being treated as null in typescript. That's why I am using a fallback. Prisma appraently don't treat null as empty string.

2023-09-08 06:04 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +            nonAdUrls: {
So if we do exact search, we also search nonAdUrls, but we don't need to search nonAdUrls in partial search? 👀

2023-09-08 06:57 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +            nonAdUrls: {
Yes, That is the requirement in IC. 😅

2023-09-08 07:59 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +  private async filterByKeyword(keyword: string): Promise<SearchResult[]> {
This method could be moved below `filterResults` as it is being used by that method so it males the file easier to read

2023-09-08 07:59 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +      case SearchElement.ALL:
This should the default case

2023-09-08 07:59 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +    return this.filterResults({ text, searchElement, searchType });
How about:

```suggestion
    return this.filterResults({ text, scope, type });
```

2023-09-08 10:23 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +        });
This should query the URL fields, not keyword, right? 🙈

2023-09-08 10:23 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +        return this.filterUrl({ text, type });
```suggestion
        return this.filterByUrl({ text, type });
```

2023-09-08 10:23 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +        return this.filterUrlAndKeyword({ text, type });
```suggestion
        return this.filterByUrlAndKeyword({ text, type });
```

2023-09-08 10:23 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +        });
Same question: Shouldn't this also query URL fields?

2023-09-08 10:23 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +      default:
Is it the requirement that we don't have the pattern search type for keyword 😵

2023-09-08 10:28 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +      default:
For keyword there is no requirement to have a pattern match. Requirement only focus on the url. For keyword it's either exact or similar words. contains query takes place of it.

2023-09-08 10:30 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +        });
It's the fallback if anything comes that match the condition. It should not just keeping a default value if invalid type comes in to return basic filtered data.

2023-09-08 11:10 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +      default:
Then it should be a if/else block not a switch case. We could also extend to support pattern for any scope.

2023-09-08 11:10 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +        });
That would be totally an unexpected side effect. The method is not doing what is says 😨

2023-09-08 11:10 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +        keyword: text ?? '',
If this method is called, `text` should not /must not be an empty string

2023-09-08 15:21 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +        });
I have moved the pattern search to the default one. And removed this.

2023-09-11 04:19 UTC, olivierobert requested changes
I recommend dropping the occurrences count to lower the complexity and get this merged

2023-09-11 04:19 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +    const { queryInput, type, scope, leastCount = 1 } = this.filters;
Setting the default value for `leastCount` is rather unexpected 🤔 Shouldnt this be defined at the interface level or in `filterResults` instead?

As a side note, `leastCount` does not seem used in the queries at all so could be dropped. to keep things simple (the queries are already complex enough).

2023-09-11 04:19 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +          sr.status
Why is status needed?

2023-09-11 04:19 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +      where
Casing inconsistency:

```suggestion
      WHERE
```

2023-09-11 04:19 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +      group by flatten.id, flatten.keyword, flatten.nod_ad_urls, flatten.ad_word_top_urls, flatten.status`
Shouldn't the results be paginated too? (using LIMIT)

2023-09-11 04:19 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +    const characterToSearch = `%${queryInput}`.repeat(leastCharacterCount).concat('%');
`leastCharacterCount` is to count the number of occurrences of that character (e.g., search for strings that have `>` at least `3` time, then the string `menu > store > categories > accessories` would be a match) but this would search for `>>>` if `leastCharacterCount` was set to `3.

2023-09-11 04:29 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +          sr.status
We are displaying status in table. That's why it is needed 🙂

2023-09-11 04:33 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +    const { queryInput, type, scope, leastCount = 1 } = this.filters;
I have dropped the filter params. https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/101/commits/89fdc82137977028981366e5b8df793bc65b19be

2023-09-11 04:53 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +    const { queryInput, type, scope, leastCount = 1 } = this.filters;
The act of passing these params(`queryInput, type, scope`) through many functions seems unnecessary too. As we are in a class and we already have `this.filters`, we just need to get these params from the `this.filters` when we need.

But since that's minor, we can skip it for now ✋

2023-09-11 07:56 UTC, tednguyendev approved these changes

2023-09-11 08:03 UTC, olivierobert approved these changes

2023-09-11 08:20 UTC, merged