Add ui feature for filtering result based on different query
nimblehq/ic-nextjs-prabesh-dahal pull request #103
Opened 2023-09-04 09:06 UTC by Prabeshpd

- Close #

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-09-06 05:47 UTC, tednguyendev commented on src/constants/constants.ts
> +export const DEFAULT_TEXT_COLOR = '#ffffff';
Since they are only being used once, let just put them in `MODAL_DEFAULT_STYLES` 🙈

2023-09-06 05:47 UTC, tednguyendev commented on src/constants/constants.ts
> +export const MODAL_DEFAULT_STYLES = {
Do people usually put constants of the FE and BE in the same file? 🤔 Thank you for your explanation in advance 🙏

2023-09-06 05:47 UTC, tednguyendev commented on src/stylesheets/base/_modal.scss
> +  }
Will this work? 👀 

```suggestion
  &__head {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    padding: 1rem;
    border-bottom-width: 1px;
    border-color: $border-color;

    & > h3 {
      font-weight: 600;
      font-size: 1.25rem;
      line-height: 1.75rem;
    }
  }
```

2023-09-06 05:47 UTC, tednguyendev commented on src/components/SearchResultList/SearchResultModalForm.test.tsx
> +describe('search result modal form', () => {
How about this 💪 

```js
describe('Search result modal form', () => {
  describe('given isOpen is true', () => {
    it('renders the component', async () => {
    });
  });

  describe('given isOpen is false', () => {
    it('does NOT render the component', async () => {
    });
  });

  describe('given form is filled', () => {
    it("submits the form's input values on submit", async () => {
    });
  });
});

```

2023-09-06 05:47 UTC, tednguyendev commented on src/components/SearchResultList/SearchResultList.tsx
We may also need to update the test for this file since this PR introduces many new things.

2023-09-06 07:03 UTC, Prabeshpd commented on src/constants/constants.ts
> +export const MODAL_DEFAULT_STYLES = {
The projects I have worked on normally have separate folders for frontend or backend or separate repositories. Since, here we have the same shared folders I used the same. This is kind of new for me too. 😅

2023-09-06 07:23 UTC, Prabeshpd commented on src/stylesheets/base/_modal.scss
> +  }
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/103/commits/621c304c6bc944c554cb40a9a211c23728dfb2f0

2023-09-06 08:14 UTC, Prabeshpd commented on src/components/SearchResultList/SearchResultList.tsx
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/103/commits/6e920b33d358c5824664e9b4166bd54302a5c927

2023-09-07 04:15 UTC, olivierobert requested changes

2023-09-07 04:15 UTC, olivierobert commented on src/components/SearchResultList/SearchResultModalForm.tsx
> +        <div className="ReactModalPortal__head">
Why is the class name casing different? And not:

```suggestion
        <div className="search-result-filter-modal__head">
```

The modal component (https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/103/files#diff-a128ba64d2993a021e074681d30d6e58fcdee69d7054604d91d63d38309ce520) should not use `ReactModalPortal` as the block element (as this comes from the library). Think of combining class names:

```react
<div data-testid="modal search-result-filter-modal">
   <Modal
        isOpen={isOpenModal}
        onRequestClose={closeModal}
        style={MODAL_DEFAULT_STYLES}
        ariaHideApp={false}
      >

  <div className="modal__head">

  #...
</div>
```

`modal` is the shared component that can be used in multiple page, while `search-result-filter-modal` can be used to target this very specific modal

2023-09-07 17:41 UTC, Prabeshpd commented on src/components/SearchResultList/SearchResultModalForm.tsx
> +        <div className="ReactModalPortal__head">
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/103/commits/e4d939d6e32197ea100fa7403e6fcf3f6d019cb6. Remove the modal using new implementaiton.

2023-09-12 06:05 UTC, tednguyendev approved these changes

2023-09-12 06:05 UTC, tednguyendev commented on src/components/SearchResultList/FilterForm.tsx
> +        await onApplyFilter(payload);
Seems like it is not needed?

```suggestion
        onApplyFilter(payload);
```

<img width="823" alt="CleanShot 2023-09-12 at 13 01 30@2x" src="https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/76901736/294e4645-fb8a-4906-81da-f69c96e0d2b6">

2023-09-12 06:05 UTC, tednguyendev commented on src/stylesheets/base/_react-select.scss
> +  color: map-get($color-white, 'primary');
Let's make it looks a bit more interactive

```suggestion
  color: map-get($color-white, 'primary');
  cursor: pointer;
```

<img width="106" alt="CleanShot 2023-09-12 at 13 03 17@2x" src="https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/76901736/27faa03c-5288-4e76-a698-a2196a3518d5">

2023-09-12 08:43 UTC, olivierobert reviewed
Mostly minor issues that needs to be tightened up

2023-09-12 08:43 UTC, olivierobert commented on src/components/SearchResultList/FilterForm.tsx
> +interface FormValues {
Same idea about naming:

```suggestion
interface FilterFormValues {
```

2023-09-12 08:50 UTC, Prabeshpd commented on src/stylesheets/base/_react-select.scss
> +  & &__control {
React select needs to pass the extender class and can be only be accessed with both of the attributes meaning

```<ReactSelect className="react-select" extendedClass="react-select" />```

And for the scss

```.react-select .react-select__control```

For avoiding too many names I used the same string for class name and extended class name. Does it make sense to add another name for extended ?
new way 
```<ReactSelect className="react-select" extendedClass="react-select-container" />```


```.react-select .react-select-container__control```

2023-09-12 10:13 UTC, tednguyendev commented on src/stylesheets/base/_react-select.scss
> +  & &__control {
By `extendedClass` you mean the prop [`classNamePrefix`](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/blob/529851b4d8afe27bb894e1cb33430f5c31478d5a/src/components/SearchResultList/FilterForm.tsx#L73) right? 👀 

Ah, so by arranging the CSS selectors(`& &__control`) like that, you increase the [CSS specificity](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/103/files) to override the style.

Yes having the comment is better 👍

2023-09-13 04:20 UTC, olivierobert approved these changes

2023-09-13 06:18 UTC, merged