[#110] [Backend] Implement scraper for Bing
nimblehq/ic-nextjs-prabesh-dahal pull request #130
Opened 2023-09-12 03:01 UTC by Prabeshpd

- Close #110 

## What happened 👀

- Add scraper for bing
- Add parser for bing
- Update scraper job to add job for bing
- Add column search engine with enum.

## Insight 📝

- Implemented scraper for bing. Added a job for bing to scrape when the file are uploaded. Have created an enum for database to store which engine searched the result. 
- In terms of parser have created a separate class with same interface as google parser. I did not create a separate parent class as the implementation is different and it is good to have a interface definition.

## Proof Of Work 📹

Passed CI pipelines for test

2023-09-12 08:56 UTC, olivierobert reviewed
Some early feedback. More will follow.

2023-09-12 08:56 UTC, olivierobert commented on src/services/parser/bingParser.test.ts
> +describe('BingParse:', () => {
SHouldnt this be:

```suggestion
describe('BingParser:', () => {
```

2023-09-12 08:56 UTC, olivierobert commented on src/services/parser/bingParser.test.ts
> +      describe('given raw html with top ad words', () => {
Any way way to limit the nesting here as it looks like [the pyramid of doom](https://en.wikipedia.org/wiki/Pyramid_of_doom_(programming)#)

2023-09-12 08:56 UTC, olivierobert commented on src/services/parser/parser.ts
> +  constructor(searchEngine: SearchEngine, htmlRawString: string) {
It would be best to raise an exception at the initialization phase:

```js
constructor(searchEngine: SearchEngine, htmlRawString: string) {
  if (!isSupportedSearchEngine(SearchEngine)) {
    throw new ParseError({ message: `Unsupported search engine: ${this.searchEngine}` });
  }

  this.searchEngine = searchEngine;
  this.htmlRawString = htmlRawString;

  return // set the parser
}

private isSupportedSearchEngine() {
  return SEARCH_ENGINES.incldues(this.searchEngine)
}
``` 

The earlier it fails the better. It would also follow the factory pattern.

2023-09-12 08:56 UTC, olivierobert commented on src/config/parserSelectorConfig.ts
> +      nonAdParent: process.env.NON_AD_PARENT_BING || '#b_results',
It might be better to leave this defined in each parse classes. these are not reused apart from tests and would help in understanding each parser better.

I also recommend dropping the need to use env variables as this does not work anymore when having more than 1 search engine. The benefits outweigh the cons. So let's keep these defined as contacts in the parser files 💡

2023-09-12 08:56 UTC, olivierobert commented on src/services/parser/bingParser.ts
> +class BingParser implements IParse<cheerio.CheerioAPI> {
How about defining a base parser that each parser muct implement. This way `IParse<cheerio.CheerioAPI>` would be defined only once (a win) and we could ensure that all parsets expose the same API.

2023-09-12 09:56 UTC, Prabeshpd commented on src/services/parser/bingParser.ts
> +class BingParser implements IParse<cheerio.CheerioAPI> {
I intentionally did not create the base class as the internal implementation are different. I wanted to bind class with interface rather than extending  it. But I think it makes sense to create a base class. Will create it.

2023-09-12 10:07 UTC, Prabeshpd commented on src/services/parser/bingParser.test.ts
> +      describe('given raw html with top ad words', () => {
I think we can remove the valid html part here as the empty string already accounts for that.

2023-09-13 04:40 UTC, olivierobert requested changes

2023-09-13 04:40 UTC, olivierobert commented on src/app/actions/upload.ts
> +          { keyword, userId: +userId, searchEngine: SearchEngine.bing }
One of them should be Google, right? This would enqueue later the scarping for Bing twice. 

```suggestion
          { keyword, userId: +userId, searchEngine: SearchEngine.google }
```

2023-09-13 04:40 UTC, olivierobert commented on src/app/actions/upload.ts
> +      (accumulator: Prisma.SearchResultCreateManyInput[], keyword) => {
It would be best to avoid `accumulator` as this is from the spec 🙈 Also, here [flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) would be sufficient:

```js
const payload = keywords. flatMap((keyword) => {
  return [
     { keyword, userId: +userId, searchEngine: SearchEngine.bind },
     { keyword, userId: +userId, searchEngine: SearchEngine.google },
  ]
})
```

2023-09-13 04:40 UTC, olivierobert commented on src/services/parser/baseParser.ts
> +  private loadHtmlDocumentApi() {
It would be best to move all private methods below all public ones for readability

2023-09-13 04:40 UTC, olivierobert commented on src/services/parser/baseParser.ts
> +    const urls: string[] = [];
Since a base class is not meant to be used directly (like an abstract class), the methods should be defined but raise a `NotImplementException` (see how Nest.JS does it: http://nestjs-doc.exceptionfound.com/classes/notimplementedexception.html)

2023-09-13 04:40 UTC, olivierobert commented on src/workers/scraper.ts
> +    const parserInstance = new Parser(searchEngine, htmlData).getParserInstance();
When using `instance`, the first thought is that we use a singleton pattern, but that is not what the code does here. So, I recommend not using that term.

It can be simplified to:

```suggestion
    const parser = new Parser(searchEngine, htmlData).getParserInstance();
```

Technically, this would also work:

```suggestion
    const parser = new Parser(searchEngine, htmlData).parser;
```

So an extra method is not needed 💡

2023-09-13 04:40 UTC, olivierobert commented on src/workers/scraper.ts
> +    const totalLinksCount = adWordsCount + nonAdUrls.length;
A line break would be nice for readability

```suggestion
    const totalLinksCount = adWordsCount + nonAdUrls.length;
    
```

2023-09-13 04:40 UTC, olivierobert commented on test/fixtures/bingParse.html
Naming-wise, how about: `bing-search-result.html`?

2023-09-13 04:40 UTC, olivierobert commented on src/workers/queueScraper.ts
> +  const searchResults = await listSearchResultByStatus(+userId);
Why do we need the plus sign: **+**userId?

2023-09-13 04:40 UTC, olivierobert commented on src/services/search/searchResult.test.ts
> +  describe('given axios call REJECTS with error', () => {
Ditto here:

```suggestion
  describe('given a failed request to fetch the search result page', () => {
```

2023-09-13 04:40 UTC, olivierobert commented on src/services/search/searchResult.test.ts
> +  describe('given axios call resolves data', () => {
Axios could be left out of the test description:

```suggestion
  describe('given a succesful request to fetch the search result page', () => {
```

2023-09-13 04:44 UTC, Prabeshpd commented on src/workers/queueScraper.ts
> +  const searchResults = await listSearchResultByStatus(+userId);
It internally maps the data to string and we may get a error. I faced a similar situation while testing. So, converting it to integer.

2023-09-14 03:59 UTC, tednguyendev commented on src/config/config.ts
> -    adLinkElementAttribute: process.env.AD_LINK_ANCHOR_ELEMENT_ATTRIBUTE || '.sVXRqc',
Let's also remove these from `.env.example`

2023-09-14 03:59 UTC, tednguyendev commented on src/services/parser/bingParser.ts
> +    adUrlElements.each((index, element) => {
As we not use `index`

```suggestion
    adUrlElements.each((_, element) => {
```

2023-09-14 03:59 UTC, tednguyendev commented on src/services/parser/parser.ts
> +        break;
👀 

```suggestion
```

2023-09-14 03:59 UTC, tednguyendev commented on src/services/search/searchResult.test.ts
> +    describe('given search engine is INVALID', () => {
Should this describe `given search engine is INVALID` inside the describe `given a successful request to fetch the search result page` 🙈 

How abt:

```ts
describe('searchResult', () => {
  describe('given search engine is "google"', () => {
    describe('given search successfully', () => {
      it('returns resolved data', async () => {
      });
    });
    describe('given search FAILED', () => {
      it('throws an error', async () => {
      });
    });
  });

  describe('given search engine is "bing"', () => {
    describe('given search successfully', () => {
      it('returns resolved data', async () => {
      });
    });
    describe('given search FAILED', () => {
      it('throws an error', async () => {
      });
    });
  });

  describe('given search engine is INVALID', () => {
    it('throws error', async () => {
    });
  });
});

```

2023-09-14 05:58 UTC, olivierobert approved these changes
Looks good 👍

2023-09-14 06:38 UTC, tednguyendev reviewed
LGTM 🤌

2023-09-14 06:39 UTC, merged

2023-09-14 07:45 UTC, tednguyendev commented
^Just realized I commented instead of approved 🤣