[#120] [Chore] Add test for cypress to run in github action
nimblehq/ic-nextjs-prabesh-dahal pull request #135
Opened 2023-09-17 04:08 UTC by Prabeshpd

- Close #

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-09-18 04:46 UTC, olivierobert commented on .github/workflows/test.yml
> +    runs-on: ubuntu-latest
UI tests can get stuck sometimes. so it is best to add a timeout:

```suggestion
    timeout-minutes: 10
    runs-on: ubuntu-latest
```

2023-09-18 04:46 UTC, olivierobert commented on .github/workflows/test.yml
> +    steps:
A DB will also be required, right?

2023-09-18 05:17 UTC, Prabeshpd commented on .github/workflows/test.yml
> +    steps:
No, I am thinking of intercepting the request to server actions and mocking the response from fixtures. Since, we are throughly checking the database interaction in backend. I was thinking checking the interaction of UI in success and errors.  

I am preparing a document of my understandings and the approaches to get verified.

2023-09-18 05:36 UTC, olivierobert commented on .github/workflows/test.yml
> +    steps:
UI tests must be as "real" as possible, i.e., they must be used to test the application exactly how the user would use it (especially when using Cypress). So, mocking is not expected.

2023-09-18 08:10 UTC, Prabeshpd commented on .github/workflows/test.yml
> +    steps:
Fixed here https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/135/commits/3c01c1a630a982c54f4a7ccdba6a1b00d5bd35b7

2023-09-18 10:27 UTC, tednguyendev commented on .github/workflows/test.yml
> +      - name: Lint
Do you think this is redundant as we already tested lint above? ✋

2023-09-18 10:27 UTC, tednguyendev commented on .github/workflows/test.yml
> +  test-ui:
Since we use the same `services` and `steps` with the current [`test` job](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/blob/98fd1bcc6100a033252b9a38359e9bc219144ea1/.github/workflows/test.yml#L11), are there anyway we can make this DRY? 👀

2023-09-18 10:27 UTC, tednguyendev commented on .github/workflows/test.yml
> +    steps:
Lets also remove [this](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/135/files#diff-271661623b3a6fdb66b408c573ac77f5c190aa725a30bd9a79cefecfa86be5ab)

2023-09-18 10:32 UTC, tednguyendev commented on test/helpers/database.reset.ts
> +    dbClient.user.deleteMany(),
Another way is to use the [cascade delete](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions). But this way works too ✋ 

```suggestion
    dbClient.user.deleteMany(),
```

2023-09-18 10:44 UTC, Prabeshpd commented on .github/workflows/test.yml
> +  test-ui:
We can define composite actions or reusable-workflow, I guess but  using it would create more hindrances and have their own limitations. I guess we can remove the lint step and use github actions of cypress which reduces the extra code. But I normally add these in each jobs as they run on a separate instance. It helps me to understand the flow more clearly. 

It is a nice context to gather more expert thoughts? cc @olivierobert

2023-09-19 04:20 UTC, olivierobert requested changes

2023-09-19 04:20 UTC, olivierobert commented on .github/workflows/test.yml
> +  test-ui:
There can be an inclination to try to reuse some of the steps, but it is best to keep these as separate as the complexity trade-offs are not worth it.

2023-09-19 04:20 UTC, olivierobert commented on cypress/e2e/signUp/signUp.cy.ts
> +  submitButton: 'sign-up-form__submit-button',
The convention is to use`data-set-id=""` and not re-using the BEM CSS class names to keep the test ID simpler:

```
inputName: 'sign-up-form-name',
inputEmail: ''sign-up-form-email',
inputPassword: 'sign-up-form--password',
submitButton: ''sign-up-form-submit',
``` 

See how it is set up: https://github.com/nimblehq/varun-web/blob/e968178cd948bab91ae748264f869564993cd729/src/setupTests.ts#L9, and used: https://github.com/nimblehq/varun-web/blob/develop/cypress/integration/Authentication/index.spec.ts

2023-09-19 04:20 UTC, olivierobert commented on cypress/support/commands.ts
> +Cypress.Commands.add('checkToastMessage', (type: 'success' | 'error', message: string) => {
How about naming it:

```suggestion
Cypress.Commands.add('hasToastMessage', (type: 'success' | 'error', message: string) => {
```

The following reads well:

```
cy.hasToastMessage('error', 'An issue occurred when creating the user account');
```

2023-09-19 04:20 UTC, olivierobert commented on cypress/support/commands.ts
> +Cypress.Commands.add('checkSpinner', (ariaLabel: string) => {
Same suggestion to improve descriptiveness of the command:

```suggestion
Cypress.Commands.add('hasActiveSpinner', (ariaLabel: string) => {
```

2023-09-19 04:20 UTC, olivierobert commented on cypress.config.ts
> +          return seedUser(email, password);
The code is quite confusing as it seems to call twice the same method (due to the usage of the same function name), but it is not. Also, the params are not defined anywhere, right? So, can't this be:

```js
async setup({ email, password }) {
   return createUser();
})
```

2023-09-19 05:11 UTC, Prabeshpd commented on cypress.config.ts
> +          return seedUser(email, password);
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/135/commits/c2c9f9d9c25a2a9da36c08f87d148ddcf12fc65e. Have created a event for setup User. Can be changed to setup once the seeding of search result takes place.

2023-09-19 06:32 UTC, olivierobert commented on cypress/support/e2e.ts
> +configure({ testIdAttribute: 'data-testid' });
The team coventions is to name it:

```suggestion
configure({ testIdAttribute: 'data-test-id' });
```

As raised in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/135#discussion_r1329552737

2023-09-19 06:32 UTC, olivierobert commented on cypress.config.ts
> +        async resetAll() {
Adding the `All` brings more confusion as it could mean also resetting mocks or env data.

So the following would be more descriptive:

```suggestion
        async resetDatabase() {
          return resetAllDatabaseTables();
        }
```

2023-09-19 06:32 UTC, olivierobert commented on cypress.config.ts
> +        async setupUser({ email, password }) {
Now I understand how this will be used after checking https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/136/files#diff-24eee1bcbd5c0632523420a2e67ab266be7c90498752546a8eb3b9021200d9e6R21

2023-09-19 06:35 UTC, tednguyendev commented on cypress/e2e/signUp/signUp.cy.ts
> +      cy.visit('/auth/signup');
Let's insert a line break to separate the `arrange` from the `act`(as in `Arrange/Act/Assert (AAA)`) ✋ 

```suggestion
      const password = 'password';
      
      cy.visit('/auth/signup');
```

2023-09-19 08:01 UTC, tednguyendev commented on cypress.config.ts
> +    setupNodeEvents(on, config) {
Unused param 👍 

```suggestion
    setupNodeEvents(on, _) {
```

2023-09-19 10:01 UTC, tednguyendev approved these changes

2023-09-19 14:02 UTC, olivierobert approved these changes

2023-09-19 23:34 UTC, merged