[#123] [Chore] Implement UI test for the search result filtering flow
nimblehq/ic-nextjs-prabesh-dahal pull request #137
Opened 2023-09-19 23:36 UTC by Prabeshpd

- Close #123 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-09-20 03:55 UTC, Prabeshpd commented on cypress/e2e/searchResults/searchResultsKeyword.cy.ts
> +      cy.get('td[headers="keyword-column"]').should('contain', queryText);
Create a command for it. It is being used multiple times

2023-09-20 03:58 UTC, olivierobert requested changes

2023-09-20 03:58 UTC, olivierobert commented on cypress/e2e/searchResults/searchResultsKeyword.cy.ts
> +      cy.task('setupUserWithSearchResults', { email, password });
Not having the test data created inside each test makes it hard to reason about assertions such as:

```
cy.get('@tableRows').should('have.length', 1);
```	

The rule of thumb is not to overengineer tests. It is best to have some code repetition in tests when that helps in understanding and managing tests. 

What I recommend is the following step in each test:

```
//  Create a user. 
// Create specific search results. The test data can change for each test.

cy.login(user); // we can pass the whole object
cy.navigateTo('search-result') // custom command to navigate to each screen
```

2023-09-20 03:58 UTC, olivierobert commented on cypress/constants/selectors.ts
While these can be shared, having a single file with tons of constants is not easy to read and manage. Since all of these seledctors are flow specific, how about moving them to each subdirectory: `login/selectors.ts`, `searchResults/selectors.ts`, etc. Then when import them we could do simplify the import to: `import * from '../../login/selectors';

2023-09-20 03:58 UTC, olivierobert commented on cypress/constants/selectors.ts
> +  loading: 'sign-up-form-loader',
Can't there be a single label for all screens? That spinner is the same, anyway.

```suggestion
  loading: 'application-loader',
```

That could be a shared constant 💡

2023-09-20 03:58 UTC, olivierobert commented on cypress/constants/selectors.ts
> +export const SIGN_UP_SELECTOR_IDS = {
Let's avoid plurals when possible. The following would work too:

```suggestion
export const SIGN_UP_SELECTOR = {
```

2023-09-20 04:42 UTC, Prabeshpd commented on cypress/constants/selectors.ts
> +export const SIGN_UP_SELECTOR_IDS = {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/137/commits/862724755b491f06f91679079206c56067191a8b

2023-09-20 04:42 UTC, Prabeshpd commented on cypress/constants/selectors.ts
> +  loading: 'sign-up-form-loader',
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/137/commits/862724755b491f06f91679079206c56067191a8b

2023-09-20 04:43 UTC, Prabeshpd commented on cypress/constants/selectors.ts
Have moved to individual folders. https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/137/commits/862724755b491f06f91679079206c56067191a8b

2023-09-20 05:17 UTC, Prabeshpd commented on cypress/e2e/searchResults/searchResultsKeyword.cy.ts
> +      cy.task('setupUserWithSearchResults', { email, password });
Makes sense. I was thinking the same. But got deviated 😅 thinking to make a global setup. Makes more sense to put control to test suites. Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/137/commits/8b58f43b403135cbf04f2cbc8ae31bbcc9662b97

2023-09-20 05:35 UTC, tednguyendev commented on cypress/constants/selectors.ts
> +export const APPLICATION_NAV_SELECTORS = {
🙈
```suggestion
export const APPLICATION_NAV_SELECTOR = {
```

2023-09-20 05:35 UTC, tednguyendev commented on cypress/e2e/signUp/selectors.ts
> +export const SIGN_UP_ARIA_LABEL = {
Don't we use this? 👀

2023-09-20 05:35 UTC, tednguyendev commented on cypress/e2e/login/selectors.ts
> +export const LOGIN_ARIA_LABEL = {
Ditto ☝️

2023-09-20 05:35 UTC, tednguyendev commented on cypress/e2e/searchResults/searchResultsUrlWithKeyword.cy.ts
Maybe `searchResultsWithUrlAndKeyword.cy.ts`

2023-09-20 05:35 UTC, tednguyendev commented on src/components/SearchResultList/FilterForm.tsx
> +            id="list-search-result-form-type"
Why do we use `id` instead of `data-test-id` 👀

2023-09-20 05:39 UTC, Prabeshpd commented on src/components/SearchResultList/FilterForm.tsx
> +            id="list-search-result-form-type"
React Selector don't embed element with data-select-id apparently. Tried it. 😅

2023-09-20 06:48 UTC, Prabeshpd commented on cypress/e2e/login/selectors.ts
> +export const LOGIN_ARIA_LABEL = {
OOps. Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/137/commits/7873beb9a686d7b5bb4cf78aa834b3a9574deb49

2023-09-21 03:20 UTC, tednguyendev approved these changes

2023-09-21 04:10 UTC, olivierobert requested changes
Since the tests are pretty long, it is best to adjust them for readability. The suggestion I have raised should be applied to all tests.

2023-09-21 04:10 UTC, olivierobert commented on cypress/e2e/searchResults/searchResultsKeyword.cy.ts
> +      cy.task('setupSearchResults', searchResultPayload);
Readability improvement suggestion:

```
const queryText = 'text_to_find';
const [ userId, email, password ]  = [1,  'dev@nimblehq.co'; 'password' ]
const searchResultPayload = [...]

cy.task('setupUser', { id: userId, email, password });
cy.task('setupSearchResults', searchResultPayload);

cy.login({ email, password });
...
```

The first three lines are part of the Arrange section, and the rest are steps for the Act section. Plabing the query text at the top allows to making of the search result payload.

2023-09-21 04:10 UTC, olivierobert commented on cypress/e2e/searchResults/searchResultsKeyword.cy.ts
> +          keyword: 'litter',
This extra search result is not really needed. We need at most 2 search results to validate the test. So lets create the minimum test data.

2023-09-21 04:17 UTC, olivierobert commented on cypress/support/commands.ts
> +  cy.findByTestId(navId).click();
This comamnd could be improved further by handling all possible pages (there are not many):

```
import { APPLICATION_NAV_SELECTOR } from '../../constants/selectors';

Cypress.Commands.add('navigateTo', (pageName: string) => {
   switch(pageName) {
      case 'searchResult': 
         cy.navigateTo(APPLICATION_NAV_SELECTOR.searchResult);
     //...

     default:
       // throw error if page not supported
   }
}
```

Then it would be easier to use: `cy.navigateTo('searchResult')` 🎉

2023-09-21 04:46 UTC, Prabeshpd commented on cypress/e2e/searchResults/searchResultsKeyword.cy.ts
> +      cy.task('setupSearchResults', searchResultPayload);
Rearranged it as per suggestion. Thank you. Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/137/commits/7679aee28952f75573eac6126ae38928270ac41e

2023-09-21 05:20 UTC, olivierobert approved these changes

2023-09-21 06:07 UTC, merged