[#2] [Chore] Add CI pipeline for test
nimblehq/ic-nextjs-prabesh-dahal pull request #26
Opened 2023-07-20 05:51 UTC by Prabeshpd

- Close #

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-07-21 07:33 UTC, olivierobert requested changes
There is currently no benefit in splitting the workfklows into 3 jobs 🤔 There is a lot of repetitions and there are no parallelism benefits (linting and test runns will be fast). Only one job might be sufficient. Then later on it might make sense to split UI and Non-UI tests if the test suite becomes too long.

2023-07-21 07:33 UTC, olivierobert commented on .github/workflows/test.yml
> +      - development
The branch name should be `develop`. Refer to: https://nimblehq.co/compass/development/version-control/branch-management/#default-branches

2023-07-21 07:33 UTC, olivierobert commented on .github/workflows/test.yml
> +      - name: Setup node and restore cached dependencies
SYntax issue:

```suggestion
      - name: Set up node and restore cached dependencies
```

2023-07-21 07:33 UTC, olivierobert commented on .github/workflows/test.yml
> +          node-version: '16'
The current latest LTS version is 18 so we should use that version

![Uploading image.png…]()

2023-07-21 07:43 UTC, Prabeshpd commented
> There is currently no benefit in splitting the workfklows into 3 jobs 🤔 There is a lot of repetitions and there are no parallelism benefits (linting and test runns will be fast). Only one job might be sufficient. Then later on it might make sense to split UI and Non-UI tests if the test suite becomes too long.

Ok. Noted

2023-07-21 07:46 UTC, Prabeshpd commented on .github/workflows/test.yml
> +          node-version: '16'
For this one. I tried setting up the project from node 18. Currently nimble eslint package `@nimblehq/eslint-config-nimble"` does not support the node 18. When I looked in the repo there was already a PR. Waiting for that PR to be merged.

2023-07-24 04:08 UTC, Prabeshpd commented on .github/workflows/test.yml
> +          node-version: '16'
Updated the node version to 18 successfully

2023-07-24 06:32 UTC, olivierobert requested changes

2023-07-24 06:32 UTC, olivierobert commented on .github/workflows/test.yml
> +      - main
There is no need to retest on merges. Sinc you work alone, make sure you rebase all your branches before merging them. Running the tests again will not catch more issues.

2023-07-24 07:28 UTC, tednguyendev approved these changes

2023-07-24 08:56 UTC, olivierobert approved these changes

2023-07-24 09:03 UTC, merged