[#22] Setup initial build for deployment
nimblehq/ic-nextjs-prabesh-dahal pull request #29
Opened 2023-07-24 07:24 UTC by Prabeshpd

- Close #

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-07-25 03:16 UTC, olivierobert requested changes

2023-07-25 03:16 UTC, olivierobert commented on .github/workflows/deployment.yml
> +  deploy-production:
This can achieved via a single job with an if condition:

```
- name: Deploy to production
   if: github.ref == 'refs/heads/main'


- name: Deploy to staging
   if: github.ref != 'refs/heads/main'
```

Altenatively, you can create two workflows `deploy-staging.yml` and `deploy-production.yml`

See the naming convention: https://nimblehq.co/compass/development/code-conventions/github-actions/#convention-3 (each action must be a verb not a noun)

2023-07-26 02:54 UTC, olivierobert requested changes
While this works and it is good research, the implementation is complex. 

If there was two different workflows, all of this complexity could be removed:

1. `deploy-staging.yml` -> handle merges to `develop`

```yaml
on:
  push:
    branches:
      - develop
```

2. `deploy-production.yml` -> handle merges to `main`

```yaml
on:
  push:
    branches:
      - main
```

It is best to strive for simplicity to ensure others can understand the code.

2023-07-26 02:59 UTC, Prabeshpd commented
> While this works and it is good research, the implementation is complex.
> 
> If there was two different workflows, all of this complexity could be removed:
> 
> 1. `deploy-staging.yml` -> handle merges to `develop`
> 
> ```yaml
> on:
>   push:
>     branches:
>       - develop
> ```
> 
> 2. `deploy-production.yml` -> handle merges to `main`
> 
> ```yaml
> on:
>   push:
>     branches:
>       - main
> ```
> 
> It is best to strive for simplicity to ensure others can understand the code.

Ok. 😄 Makes sense. Will make two different pipeline for staging and main. It will make the code more easier to understand.

2023-07-27 03:04 UTC, olivierobert requested changes
The usage of PR drafter is fine as it is also used in numerous internal projects, e.g., https://github.com/nimblehq/android-templates/blob/develop/.github/workflows/draft-new-release.yml. However, I still find the implementation complex.

2023-07-27 03:04 UTC, olivierobert commented on .github/workflows/deploy_production.yml
> +        run: echo "release=true" >> $GITHUB_ENV
Every branch merged to `main` will be a release. What is the use case you see for having this complex check?

2023-07-27 03:04 UTC, olivierobert commented on .github/workflows/deploy_production.yml
> +      staging: ${{env.staging}}
Why is this required since this workflow will only deploy to production?

2023-07-27 03:07 UTC, Prabeshpd commented on .github/workflows/deploy_production.yml
> +      staging: ${{env.staging}}
Forgot to remove this one. 🙈

2023-07-27 03:09 UTC, Prabeshpd commented on .github/workflows/deploy_production.yml
> +        run: echo "release=true" >> $GITHUB_ENV
Just wanted to make sure that if the branch merged to master has no release branch associated with them to not to release them. If the developer intentionally pushes the code without wanting them on production. But thinking out loud it makes sense to remove them completely 😅. Since, we are releasing all the code that are on main it makes sense to remove them completely.

2023-07-27 03:14 UTC, Prabeshpd commented on .github/workflows/deploy_production.yml
> +      staging: ${{env.staging}}
Fixed on https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/29/commits/86be14e47c56f50d6b0c1196594572f0738ef52d

2023-07-27 03:15 UTC, Prabeshpd commented on .github/workflows/deploy_production.yml
> +        run: echo "release=true" >> $GITHUB_ENV
Fixed on https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/29/commits/86be14e47c56f50d6b0c1196594572f0738ef52d

2023-07-27 07:22 UTC, olivierobert approved these changes

2023-07-27 07:23 UTC, tednguyendev approved these changes

2023-07-27 09:08 UTC, merged