[#14] Add logger for the project using pino
nimblehq/ic-nextjs-prabesh-dahal pull request #43
Opened 2023-07-31 05:33 UTC by Prabeshpd

- Close #

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-07 03:51 UTC, olivierobert requested changes
All files in `utils` should be moved to `lib`. It is best to have `lib` and `helpers` directories.

This PR is doin too much, thus lenghtneing the implementation time and making the code review harder 🤯 It is best to have separate chores to add the migration workflows. improved the Logger,  and even for the feature for exponential backoff (it is not required if we scrape only one keyword). 

> [!Warning]
> Prefer to adopt an iterative process with small pieces of work merged regularly.

2023-08-07 03:51 UTC, olivierobert commented on .github/workflows/migrate_production.yml
> +name: Migrate Database Schema To Production
This should be an extra step in the exsting workflows for `deploy_staging` and `deploy_production`. Just like building the JS files, migrating the DB is part of the deployment workflow.

2023-08-07 03:51 UTC, olivierobert commented on src/constants/enums.ts
> +export const ERROR_CODES = new Map<ERROR_TYPES, number>([
Technically this is not an enum so the file might better be named `error.ts`. Also avoid plural whenever possible: https://nimblehq.co/compass/development/code-conventions/#convention-15

2023-08-07 03:51 UTC, olivierobert commented on src/lib/worker.test.ts
> +    await bullMq.addJob({ name: 'asfd', opts: {}, data: {} });
`options` was better because abbreviations should be avoided: https://nimblehq.co/compass/development/code-conventions/#convention-12

2023-08-07 03:51 UTC, olivierobert commented on src/workers/buildScraper.ts
> +  const delayer = new Delayer<IScraperData>(
The whole delying mechanism is too complex 😵 A simpler solution would be to use the `delay` option (https://docs.bullmq.io/guide/jobs/delayed) and calculate an exponentail delay value, e.g.  job #1 -> delay is 0, job #2 -> delay is 2s, job #3 -> delay is 4s, job #4 -> delay is 12s, etc. 

> [!Note]
> This is called exponental backoff: https://en.wikipedia.org/wiki/Exponential_backoff 🧑‍🏫

2023-08-07 04:04 UTC, Prabeshpd commented on src/lib/worker.test.ts
> +    await bullMq.addJob({ name: 'asfd', opts: {}, data: {} });
BullMq jobs interface has native opts keyword. So, went with the opts keyword

2023-08-07 04:10 UTC, Prabeshpd commented on src/workers/buildScraper.ts
> +  const delayer = new Delayer<IScraperData>(
😅 I was doing the same thing as the delay option in bullmq but in more complicated way. Will use bullmq delayer.

2023-08-07 04:16 UTC, Prabeshpd commented
> All files in `utils` should be moved to `lib`. It is best to have `lib` and `helpers` directories.
> 
> This PR is doin too much, thus lenghtneing the implementation time and making the code review harder 🤯 It is best to have separate chores to add the migration workflows. improved the Logger, and even for the feature for exponential backoff (it is not required if we scrape only one keyword).
> 
> Warning Prefer to adopt an iterative process with small pieces of work merged regularly.

Ok. Noted. Was planning to break the PR once the feature was completed and then make separate issue for each PR. But makes sense to separate them beforehand and plan them more properly. Will improve this on the upcoming tasks 🙂

2023-08-07 07:20 UTC, Prabeshpd commented on src/workers/buildScraper.ts
> +  const delayer = new Delayer<IScraperData>(
Fixed in [038e5ab](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/43/commits/038e5abc75968d27c81099ae677e152a17b09cfd)

2023-08-07 10:49 UTC, tednguyendev commented on src/services/parser.test.ts
> +    const rawHtmlString = `
This can be extracted to a separate HTML file.

Doing that will make the code here looks more neat, plus, as we put them in an HTML file, the text editors will apply syntax highlighting to the text in HTML files, making it looks even better! 👐

2023-08-07 10:49 UTC, tednguyendev commented on src/workers/scraper.ts
> +    const topAdParsed = parserInstance.parseTopAdWordList(htmlDocumentAPI);
Do you thing the action of passing `htmlDocumentAPI` into the parse functions a little bit repetitive? 🤔 

I don't know if this is the Javascript way, but can we just save the `htmlDocumentAPI` into the Parser instance when we calls `loadHtmlDocumentApi` like this?

```js
class Parse implements IParse {
  htmlDocumentAPI: any;

  loadHtmlDocumentApi() {
    this.htmlDocumentAPI = cheerio.load(this.htmlRawString);
  }
}
```

Then we can just:
```js
const topAdParsed = parserInstance.parseTopAdWordList();
const bottomAdParsed = parserInstance.parseBodyAdWordList();
const nonAdParsed = parserInstance.parseNonAdWordList();
```

2023-08-07 10:49 UTC, tednguyendev commented on src/workers/scraper.ts
> +        userId: 1,
Why are we hardcoding the `userId`? 👀

2023-08-07 10:49 UTC, tednguyendev commented on src/workers/scraper.ts
> +        userId: 1,
You can always add some comments or use the PR description to explain things that look strange but has their hidden meanings before opening a PR ✋

2023-08-07 10:49 UTC, tednguyendev commented on src/services/parser.ts
> +    const urls: string[] = [];
A mini tip I use to make code clean is to only declare variables only when I need them.

Yes, this function needs the `urls`, but if we declare it on line 40(above the `adUrlElements.each`, which uses `urls`), that will reduce the mild confusion when the developers move their eyes from line 32 to 43, wondering why the code still not use this `urls` 😆

2023-08-08 00:12 UTC, Prabeshpd commented on src/workers/scraper.ts
> +    const topAdParsed = parserInstance.parseTopAdWordList(htmlDocumentAPI);
Yes, the initial thought was to do this. Since, typescript doesn't track this mutation in that case and it makes us compulsory to initialize the property in constructor. To mitigate that I have to either use IIFE function or make them any type or add null type to initialize it to value. Again coming to parse function I have to check in every instance whether the property has value or not which adds more repetitive code. So, have gone for this approach. Since here, we only have to pass variable to function. If the code would be repetitive would have gone with the above approach.

2023-08-08 00:16 UTC, Prabeshpd commented on src/services/parser.ts
> +    const urls: string[] = [];
😄 . It is a javaScript convention to declare variables at the top. As per my knowledge before the use of let and const the variables are not blocked scoped so defining variable down would hoist them and sometime may leave the variables undeclared so, was made convention to declare variables in the top. Since, let and const as they are block scoped we can declare them later.

2023-08-08 00:20 UTC, Prabeshpd commented on src/services/parser.test.ts
> +    const rawHtmlString = `
If a separate file is declared then again I have to add other helper function to read and parse the file while importing it. Since, the raw string are small and maintained proper spacing I had opted for directly defining them here. If the file are big and needed much more frequently would have gone for that approach.

2023-08-08 00:21 UTC, Prabeshpd commented on src/workers/scraper.ts
> +        userId: 1,
OOPS. 🙈  Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/43/commits/ee0896e5344d5362ad2487d35aa77e50395d7210.

2023-08-08 02:30 UTC, tednguyendev commented on src/services/parser.ts
> +    const urls: string[] = [];
I see, so that's another reason why people use `var` these days, right? 🤔 Thanks for your explanation.

2023-08-08 02:36 UTC, Prabeshpd commented on src/services/parser.ts
> +    const urls: string[] = [];
I think you meant that people `don't` use `var`😅  right?

2023-08-08 02:36 UTC, tednguyendev commented on src/workers/scraper.ts
> +    const topAdParsed = parserInstance.parseTopAdWordList(htmlDocumentAPI);
> it makes us compulsory to initialize the property in constructor.

So you means that, by doing this, it will work? 👀
```js
class Parse implements IParse {
  selectorIds: ISelectorId;
  htmlRawString: string;
  htmlDocumentAPI: any;

  constructor(selectorIds: ISelectorId, htmlRawString: string) {
    this.selectorIds = selectorIds;
    this.htmlRawString = htmlRawString;
    this.htmlDocumentAPI = cheerio.load(this.htmlRawString);
  }
}
```

Can we do that? 🤔

2023-08-08 02:46 UTC, Prabeshpd commented on src/workers/scraper.ts
> +    const topAdParsed = parserInstance.parseTopAdWordList(htmlDocumentAPI);
yes, we can do that. 😄 . I was just trying to make the class independent of library. But thinking out loud it just makes the interface dependent on the library 😅. Will go for this approach.

2023-08-08 02:55 UTC, Prabeshpd commented on src/workers/scraper.ts
> +    const topAdParsed = parserInstance.parseTopAdWordList(htmlDocumentAPI);
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/43/commits/2b704b3a699327a3742c07232e567214524b4ca1

2023-08-08 03:15 UTC, tednguyendev commented on src/services/parser.ts
> +    const urls: string[] = [];
Ah yes 🤣

2023-08-08 03:27 UTC, tednguyendev approved these changes

2023-08-08 06:05 UTC, olivierobert requested changes
This pull request is very large and there is too many implementation details. So it will take time to have it merged 😓

2023-08-08 06:05 UTC, olivierobert commented on src/workers/scraper.test.ts
> +    mockClear(search.searchResult);
Doesn't `jest.resetAllMocks` or `jest.restoreAllMocks` do the same?

2023-08-08 06:05 UTC, olivierobert commented on src/workers/scraper.test.ts
> +    expect(Parse.prototype.parseBodyAdWordList).toHaveBeenCalledTimes(1);
Why do we need to spy on the prototype method? Wouldn't https://jestjs.io/docs/jest-object#jestspyonobject-methodname work? The mway the mock object was set `search as jest.Mocked<typeof search>;` is rather odd/unexpected.

2023-08-08 06:30 UTC, closed without merging