[#14] Add support for the database functionalities
nimblehq/ic-nextjs-prabesh-dahal pull request #44
Opened 2023-08-02 09:40 UTC by Prabeshpd

- Close #

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-03 03:54 UTC, olivierobert commented
@Prabeshpd  The PR title must match the Issue: "[Backend] As a user, my uploaded keywords are scraped and saved once uploaded". The process is to have one branch + PR for each story.

2023-08-03 04:01 UTC, Prabeshpd commented
> @Prabeshpd The PR title must match the Issue: "[Backend] As a user, my uploaded keywords are scraped and saved once uploaded". The process is to have one branch + PR for each story.
> 
> Note I fixed the merged PRs to follow this convention as us - code reviewers - failed to notice this issue previously 🙈

Ok. 😄 Will create a separate issue for this one. Since this came while I was working is it ok to create a new issue and add it to this sprint? If I put in the same PR the PR will have lot of changes 🙈 . It seems I underestimated this issue to further break it down

2023-08-03 07:54 UTC, tednguyendev commented on prisma/schema.prisma
> +  id           Int            @id @default(autoincrement())
Why should we change it from `String` to `Int`? 👀

2023-08-03 07:54 UTC, tednguyendev commented on prisma/migrations/20230803044907_camel_case/migration.sql
> +DROP COLUMN "ad_words_count",
I think we should use only 1 migration file, which will create both `search_results` table and use the camel case fields instead of using 2 migration files(this file and [the previous file](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/44/files#diff-bdb9ea9dbfc956baeb941e46d8cd9a6b0601822efbd5a9b7c3e6c0befac944d7R1-R21)).

2023-08-03 07:54 UTC, tednguyendev commented on src/lib/crypt.ts
> +  const isSame = await bcrypt.compare(value, hashedValue);
How about just return the `await bcrypt.compare(value, hashedValue)` without using any variables like `isSame` 🙈

2023-08-03 07:54 UTC, tednguyendev commented on src/lib/crypt.ts
> +  const isSame = await bcrypt.compare(value, hashedValue);
And the `compare` function will be used for the next PR right? 👀

2023-08-03 07:57 UTC, tednguyendev commented
Ah, and I just realized that maybe the PR does not have enough tests yet, although the status of the PR is in review, and the the box `Add the tests` is ticked as done in the PR. So I will come back later and do more reviews! ✋

2023-08-03 08:01 UTC, Prabeshpd commented
> Ah, and I just realized that maybe the PR does not have enough tests yet, although the status of the PR is in review and the box `Add the tests` in the PR description is ticked as done. So I will come back later and do more reviews! ✋

Test are still left. I am adding the test on search Results too. It seems I have mistakenly ticked the add test task

2023-08-03 08:02 UTC, Prabeshpd commented on src/lib/crypt.ts
> +  const isSame = await bcrypt.compare(value, hashedValue);
Will remove this function. Seems remanent of the rebase done in earlier PR 🙈

2023-08-03 08:04 UTC, Prabeshpd commented on prisma/schema.prisma
> +  id           Int            @id @default(autoincrement())
Since, it is a primary field for user. It does not make sense to make it specifically uuid as per now requirement. So, changed it to integer

2023-08-03 08:22 UTC, tednguyendev commented on prisma/schema.prisma
> +  id           Int            @id @default(autoincrement())
I think it's still a normal thing to use UUIDs for primary fields, but yeah, for simple use cases like ours, we can just use id for simplicity. 👌

2023-08-04 03:13 UTC, tednguyendev approved these changes
LGTM.

But I think the scope of this PR, as stated on [the issue](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/issues/45), should only be about setting up the database and creating migration files.

The repository files should be added later, when we need to actually use them. Having them early on this PR causes no harm, but without the code that actually uses them, I find it hard to review as a whole flow. For example, [this file](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/44/files#diff-69ac28b9f3b3bdefd2d5040cb90c72b233ff05a82b15545348fcfb0beddaeb7bR6) can be added on the PR to solve [this ticket](https://github.com/orgs/nimblehq/projects/59?pane=issue&itemId=33408557) instead.

2023-08-04 03:23 UTC, Prabeshpd commented
> LGTM.
> 
> But I think the scope of this PR, as stated on [the issue](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/issues/45), should only be about setting up the database and creating migration files.
> 
> The repository files should be added later, when we need to actually use them. Having them early on this PR causes no harm, but without the code that actually uses them, I find it hard to review as a whole flow. For example, [this file](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/44/files#diff-69ac28b9f3b3bdefd2d5040cb90c72b233ff05a82b15545348fcfb0beddaeb7bR6) can be added on the PR to solve [this ticket](https://github.com/orgs/nimblehq/projects/59?pane=issue&itemId=33408557) instead.

Yes, It makes sense to place in the PR that we can use. Only thought here was to add the database related file in one PR. I was trying to segregate the scope of PR on the domain that I was working on. But it makes sense to add them on the time of use of these functions. Will keep that in mind on my upcoming PR. Thank you @tednguyendev

2023-08-04 03:41 UTC, olivierobert requested changes
Mostly some minor naming issues ✌️

2023-08-04 03:41 UTC, olivierobert commented on prisma/migrations/20230803092725_search_result/migration.sql
It would be best to split the creation of multiple tables into multiple migrations:
- one migration to create users
- one migration to create search_results

Not a blocker but this is how we would normally do it 😅

2023-08-04 03:41 UTC, olivierobert commented on src/lib/crypt.test.ts
> +    it('should generate hash for the string', async () => {
Avoid the old syntax `should`, prefer the imperative tone:

```suggestion
    it('generates a hash for the string', async () => {
```

2023-08-04 03:41 UTC, olivierobert commented on src/lib/crypt.test.ts
> +      const result = await hash(str);
Minor rename suggestion to avoid using too generic variable names such as `data` or `results`:

```suggestion
      const hash = await hash(str);
```

or 

```suggestion
      const generatedHash = await hash(str);
```

2023-08-04 03:41 UTC, olivierobert commented on src/lib/crypt.test.ts
> +      const str = 'test';
Avoid abbreviated variable names (see: https://nimblehq.co/compass/development/code-conventions/#convention-12) and naming after object types (see: https://nimblehq.co/compass/development/code-conventions/#convention-16):

```suggestion
      const inputText = 'test';
```

2023-08-04 03:41 UTC, olivierobert commented on src/repositories/searchResult.ts
> +export const listSearchResultForScraping = async (userId: number) => {
This method name is a bit inconsistent (the suffix `ForScraping` is added only this method and seems redundant):

```suggestion
export const listSearchResult = async (userId: number) => {
```

2023-08-04 05:20 UTC, Prabeshpd commented on src/repositories/searchResult.ts
> +export const listSearchResultForScraping = async (userId: number) => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/44/commits/772649044e477fe0425328fbaae9c5acd0eccb73

2023-08-04 05:20 UTC, Prabeshpd commented on src/lib/crypt.test.ts
> +      const str = 'test';
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/44/commits/772649044e477fe0425328fbaae9c5acd0eccb73

2023-08-04 05:20 UTC, Prabeshpd commented on src/lib/crypt.test.ts
> +      const result = await hash(str);
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/44/commits/772649044e477fe0425328fbaae9c5acd0eccb73

2023-08-04 05:20 UTC, Prabeshpd commented on src/lib/crypt.test.ts
> +    it('should generate hash for the string', async () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/44/commits/772649044e477fe0425328fbaae9c5acd0eccb73

2023-08-04 05:21 UTC, Prabeshpd commented on prisma/migrations/20230803092725_search_result/migration.sql
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/44/commits/08199ffc4324f5b577b4f131651de64d27baac0c

2023-08-04 06:05 UTC, olivierobert approved these changes

2023-08-04 06:41 UTC, merged