Feature/backend upload csv file
nimblehq/ic-nextjs-prabesh-dahal pull request #59
Opened 2023-08-10 02:37 UTC by Prabeshpd

- Close #

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-10 03:27 UTC, olivierobert commented on src/app/api/v1/upload/route.ts
> +    }
It would be best to keep the route/controller lean. Moving this business logic to a separate object is best. See app/actions in https://github.com/nimblehq/js-framework-benchmark/blob/develop/nextjs-13/src/app/actions/actions.tsx

2023-08-10 05:58 UTC, tednguyendev commented on src/app/api/v1/upload/route.ts
> +}
I thought we were gonna use [server actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions) instead of the API way 👀

2023-08-10 05:58 UTC, tednguyendev commented on src/lib/file.ts
> +    throw new Error('unable to process file');
You can either choose to capitalize or not with the error message, but I think we should make it consistent with the [other errors](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/59/files#diff-e2edb59306703697af6f649f96e9a72a549261292404e8aac82f40ae29d2085aR9) 🙈

2023-08-10 05:58 UTC, tednguyendev commented on test/api/upload.test.ts
> +  it('', async () => {
Why should we let the example name empty? 🤔

2023-08-10 05:58 UTC, tednguyendev commented on test/fixtures/user.ts
> +export const userUpload: User = {
Why don't we just use one `user` fixture? 👀

2023-08-10 06:00 UTC, tednguyendev commented
Btw, I think it will be better if you put the real work result in the `Proof Of Work 📹`. For example, maybe you can put an image to call the Postman? Because we already have the workflow to run the tests, putting the image to show that the tests passed is kind of, duplicated? 🙈

2023-08-10 06:21 UTC, Prabeshpd commented on test/fixtures/user.ts
> +export const userUpload: User = {
Jest are not running the test suite sequentially. There is an error before adding two sets of data on the database. So, using different fixtures so that the data are not duplicated or hit the constraint of table. 
I tried running the them in band to run sequentially. Although the it is run sequentially, the describe suite parts seemed to run early especially the before section where the database is cleaned and inserted with data.

2023-08-10 06:22 UTC, Prabeshpd commented
> Btw, I think it will be better if you put the real work result in the `Proof Of Work 📹`. For example, maybe you can put an image to call the Postman? Because we already have the workflow to run the tests, putting the image to show that the tests passed is kind of, duplicated? 🙈

Ok. 😄

2023-08-10 06:24 UTC, Prabeshpd commented on test/fixtures/user.ts
> +export const userUpload: User = {
More appropriate would be to have factories I guess as suggested by Olivier in other PR. Using factories I can create new User object using spread operator. The changed files are already too many. I am thinking of creating new chore ticket in the upcoming sprint. Would it be ok?

2023-08-10 07:33 UTC, tednguyendev commented on src/app/api/v1/upload/route.ts
> +}
So you mean the server actions can't receive CSV files? 🤔

2023-08-10 07:34 UTC, tednguyendev commented on test/fixtures/user.ts
> +export const userUpload: User = {
I see. Thanks for your explaining ✋

2023-08-10 08:49 UTC, Prabeshpd commented on src/lib/file.ts
> +    throw new Error('unable to process file');
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/59/commits/e8b36719b56ea4f5a935b3db2aed37835eb744b0

2023-08-10 08:49 UTC, Prabeshpd commented on test/api/upload.test.ts
> +  it('', async () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/59/commits/e8b36719b56ea4f5a935b3db2aed37835eb744b0

2023-08-10 08:50 UTC, Prabeshpd commented on src/app/api/v1/upload/route.ts
> +    }
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/59/commits/e8b36719b56ea4f5a935b3db2aed37835eb744b0

2023-08-10 08:52 UTC, tednguyendev commented on src/app/api/v1/upload/route.ts
> +}
Understood. Thank you!

2023-08-11 02:27 UTC, tednguyendev approved these changes

2023-08-11 03:51 UTC, olivierobert requested changes

2023-08-11 03:51 UTC, olivierobert commented on src/app/actions/upload.ts
> +export async function handleCsv(file: FormDataEntryValue | null, userId: number) {
Naming-wise, what do you think of the following:

```suggestion
export async function uploadCsv(file: FormDataEntryValue | null, userId: number) {
```

It is simple and correspond more or less to teh file name. I do not see value in having the prefix `handle` 🤔

2023-08-11 03:51 UTC, olivierobert commented on src/app/actions/upload.ts
> +    const tags = await parseCSVFormData(file);
I am unsure why you kept wanting to name this `tags`, wouldn't the following make more sense 😅 

```suggestion
    const keywords = await parseCSVFormData(file);
```

2023-08-11 03:51 UTC, olivierobert commented on src/lib/file.ts
> +  // Convert stream to buffer
Whenver you feel like the need to add a comment, think of extracting the code to a function:

```javascript
const convertToBuffer(stream: AsyncIterable<any>) {
   const chunks = [];

   for await (const chunk of stream) {
     chunks.push(chunk);
  }

  return Buffer.concat(chunks).toString();
}

export async function parseCSVFormData(file: FormDataEntryValue): Promise<string[]> {
  // ...
  const bufferString = convertToBuffer(stream)

  return bufferString.split(',\n').map((data) => data.trim());
}
```

It makes the code more readable 🧑‍🏫

2023-08-11 03:51 UTC, olivierobert commented on src/lib/file.ts
> +    throw new Error('Only Csv file is supported');
Sinc eit is an acronym, it should be:

 ```suggestion
    throw new Error('Only CSV file is supported');
```

In addition the message could be improved to:

 ```suggestion
    throw new Error('The file is of the incorret expected type (CSV)');
```

2023-08-11 03:51 UTC, olivierobert commented on test/actions/upload.test.ts
> +    console.log({ searchResultKeyword });
That should be removed as it looks like for debugging only

2023-08-11 04:07 UTC, Prabeshpd commented on test/actions/upload.test.ts
> +    console.log({ searchResultKeyword });
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/59/commits/60c2b4b73860a885a6a8b0065d51e0ec37930de6

2023-08-11 04:07 UTC, Prabeshpd commented on src/lib/file.ts
> +    throw new Error('Only Csv file is supported');
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/59/commits/60c2b4b73860a885a6a8b0065d51e0ec37930de6

2023-08-11 04:08 UTC, Prabeshpd commented on src/lib/file.ts
> +  // Convert stream to buffer
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/59/commits/b5f42d1ea18df0181c47a66fe2fa1549da29515f

2023-08-11 04:08 UTC, Prabeshpd commented on src/app/actions/upload.ts
> +    const tags = await parseCSVFormData(file);
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/59/commits/60c2b4b73860a885a6a8b0065d51e0ec37930de6

2023-08-11 06:01 UTC, olivierobert approved these changes

2023-08-11 06:06 UTC, merged