[#8] [UI] As a user, I can upload csv files
nimblehq/ic-nextjs-prabesh-dahal pull request #60
Opened 2023-08-11 02:41 UTC by Prabeshpd

- Close #

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-14 05:29 UTC, tednguyendev commented on src/app/upload/page.tsx
> +      const response = await fetch('http://localhost:3000/api/v1/upload', {
The reason you do not create a reusable `fetch` like [this](https://github.com/nimblehq/js-framework-benchmark/blob/develop/nextjs-12/src/lib/request/manager.ts) is that you will only call API once here, since on later PRs, you will use server actions, right?

2023-08-14 05:29 UTC, tednguyendev commented on src/app/upload/page.tsx
> +      const response = await fetch('http://localhost:3000/api/v1/upload', {
Also, putting the URL in the .env file will be better.

2023-08-14 05:29 UTC, tednguyendev commented on src/app/upload/page.tsx
> +      toast.success(data.message, {
As for the `toast`, we will reuse it many times. We can extract it into `/lib/toast/makeToast.ts` ✋ I learned it [from Beckham](https://github.com/nimblehq/js-framework-benchmark/pull/106#discussion_r1218939000) recently

2023-08-14 05:29 UTC, tednguyendev commented on src/components/common/FileUploader.tsx
> +  allowedMimeTypes: string[];
Why do we need to pass the `allowedMimeTypes` around dynamically as a variable instead of hardcoding it, when we already know that the only file type we receive is csv? 🤔

2023-08-14 05:29 UTC, tednguyendev commented on src/components/common/FileUploader.test.tsx
> +        screen.getByText('Upload the csv file with tags you want to search')
We prefer the word `keywords` than `tags`, right? 🙈

2023-08-14 05:29 UTC, tednguyendev commented on src/components/common/FileUploader.tsx
> +          <h3 className="mb-4">Upload the csv file with tags you want to search</h3>
Same as above, `tags` <> `keywords`

2023-08-14 05:29 UTC, tednguyendev commented on src/app/upload/page.test.tsx
> +        screen.getByText('Upload the csv file with tags you want to search')
Same as above, `tags` <> `keywords`

2023-08-14 05:29 UTC, tednguyendev commented on src/components/common/FileUploader.tsx
> +    formData.append('userId', '1');
hello `userId: 1` again 🙈

2023-08-14 05:29 UTC, tednguyendev commented on src/components/common/FileUploader.tsx
> +      <div>{file && `${file.name} - ${file.type}`}</div>
Would it be better if we do this instead:

```jsx
file && (<div>`${file.name} - ${file.type}`</div>)
```

To avoid an empty div, I think 👀

2023-08-14 05:29 UTC, tednguyendev commented on src/components/common/FileUploader.tsx
> +          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded "
Redundant space at the end ✋ 

```html
"rounded "
```

2023-08-14 05:29 UTC, tednguyendev commented on src/app/api/v1/upload/route.ts
> +    const file = formData.get('keywords');
Why do we change it from `file` to `keywords` but still use the `file` variable for it? 🤔

2023-08-14 05:53 UTC, Prabeshpd commented on src/app/upload/page.tsx
> +      const response = await fetch('http://localhost:3000/api/v1/upload', {
Yes, I am planning to use server actions and this was one time use so I am not creating a separate lib file for it. If there is a need then I will create a separate file

2023-08-14 05:55 UTC, Prabeshpd commented on src/app/upload/page.tsx
> +      toast.success(data.message, {
For this I was thinking the same. Since, this PR had a lot of file changes for setup. I did not make a separate file for it. For user signup there will be less file. I was planning to add it on that PR. Since, on that PR we will have a chance to use it again. 
Will that be Ok?

2023-08-14 05:56 UTC, Prabeshpd commented on src/components/common/FileUploader.tsx
> +  allowedMimeTypes: string[];
I wanted to make the upload component little bit dynamic supportive for future. As, it is placed under separate common component folder I wanted to make it reusable. We can remove it for the IC use case.

2023-08-14 05:57 UTC, Prabeshpd commented on src/components/common/FileUploader.test.tsx
> +        screen.getByText('Upload the csv file with tags you want to search')
😅 I keep getting  mixed with keywords and tags. I will add a checklist before making it ready from next time. 🙈

2023-08-14 05:59 UTC, Prabeshpd commented on src/components/common/FileUploader.tsx
> +    formData.append('userId', '1');
Here I am putting it intentionally. Since, the user login feature is not there. We are making a file directly for upload. Will keep it in a separate constant variable.

2023-08-14 06:01 UTC, Prabeshpd commented on src/app/api/v1/upload/route.ts
> +    const file = formData.get('keywords');
I wanted to make a meaningful name for frontend on what we are trying to upload. In the backend I think we can rename it to `keywordFile`. I avoid using keywords for extraction because I wanted to make clear that the received object is still file and not parsed. I will change it to `keywordFile`.

2023-08-14 06:19 UTC, tednguyendev commented on src/app/upload/page.tsx
> +      toast.success(data.message, {
Sure! Let's change it later

2023-08-14 06:26 UTC, tednguyendev commented on src/components/common/FileUploader.tsx
> +    formData.append('userId', '1');
I see. 

But in case we need to hardcode it, I think it's still better to hardcode it on the backend, since, eventually, we will get the `userId` from the session(or something familiar) on the backend, as we should not pass the `userId` from the FE and hope the BE can trust it 🙈 , like

```js
// const userId = session.user.id
const userId = '1'
```

But ya, putting it on FE is still ok for now 👍

2023-08-14 08:26 UTC, Prabeshpd commented on src/app/api/v1/upload/route.ts
> +    const file = formData.get('keywords');
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/60/commits/64bad1de85d43b7a681298c5cd1380f208f90fb3

2023-08-15 07:45 UTC, olivierobert requested changes

2023-08-15 07:45 UTC, olivierobert commented on src/app/actions/upload.ts
> +      throw errorConstruct;
What is the point of this variable renaming? `construct` is very abstract as a concert as it makes it harder to understand. IMO I do not see making such a change. This change seems uncalled for as it is not motivated by functionality to application changes 😵

2023-08-15 07:45 UTC, olivierobert commented on src/app/page.tsx
> +    <main className="home">
Such classes should be added to the body class, not internal DOM elements so that whole pages can be targeted by this selector (as done by https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/60/files#diff-dc3aadb1350da3694573e4fa0ae98f4149ed4f4c586ad65d44f1db975c671275). It is not a blocker, but it is a best practice. See for a Rails project: https://github.com/nimblehq/mia-web/blob/development/engines/mia_account/app/views/layouts/mia_account/application.html.slim#L15

2023-08-15 07:45 UTC, olivierobert commented on src/app/upload/page.test.tsx
> +  it('renders component', async () => {
Not correct English:

```suggestion
  it('renders the component', async () => {
```

2023-08-15 07:45 UTC, olivierobert commented on src/components/common/FileUploader.test.tsx
> +  it('calls onUpload function on submit button', async () => {
Never test implementation details ⚠️ It is better to test that a callback function is called. It seems like a minor change but if the callback prop is changed from `onUpload` to `onAfterUpload`, the test will still be current and valid.

2023-08-15 07:45 UTC, olivierobert commented on src/components/common/FileUploader.tsx
Why creating a sub-directory for `common`? 🤔 Since the application is small, all components can be in the main `components` root. It is no use to over-engineer before there is a need.

2023-08-15 07:45 UTC, olivierobert commented on src/components/common/FileUploader.tsx
> +    formData.append('userId', '1');
It is better to add: `TODO: replace with current user ID` to 1) avoid raising comments 😉 and 2) ensure it is not forgotten (ost text editors can programmatically check for this).

2023-08-15 07:45 UTC, olivierobert commented on src/components/common/FileUploader.tsx
> +            onChange={onFileAdd}
It is better to keep the prop value with its name:

```suggestion
            onChange={onChange}
```

2023-08-15 07:45 UTC, olivierobert commented on src/config/ui.ts
> +  SERVER_URL: process.env.REACT_BASE_ENV_URL || '',
If this is empty, then this would break. Should't an error be raised if it is missing?

2023-08-15 08:19 UTC, Prabeshpd commented on src/app/page.tsx
> +    <main className="home">
Ok. I was also thinking the same to extract the class. Since, the changes are too much in this PR? Can I create a chore task to extract the css class to separate file. And do the styling part there?

2023-08-15 08:21 UTC, Prabeshpd commented on src/components/common/FileUploader.test.tsx
> +  it('calls onUpload function on submit button', async () => {
Ok. Makes a lot of sense. Will avoid these kinds of test in future.

2023-08-15 09:14 UTC, Prabeshpd commented on src/app/actions/upload.ts
> +      throw errorConstruct;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/60/commits/f39f88caceb4aa855717251b62a0344199b35bca

2023-08-15 09:14 UTC, Prabeshpd commented on src/components/common/FileUploader.tsx
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/60/commits/b5c65f5fc0b6b4b2cf932a7de836e723f11cbb49

2023-08-15 09:15 UTC, Prabeshpd commented on src/components/common/FileUploader.test.tsx
> +  it('calls onUpload function on submit button', async () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/60/commits/b5c65f5fc0b6b4b2cf932a7de836e723f11cbb49

2023-08-16 05:18 UTC, olivierobert approved these changes
Good to go now 🚀

2023-08-16 05:18 UTC, olivierobert commented on src/app/page.tsx
> +    <main className="home">
Sure, that can be done in a separate chore 👍

2023-08-16 06:27 UTC, merged