[#1] [Backend] As a user, I can sign up with email and password
nimblehq/ic-nextjs-prabesh-dahal pull request #64
Opened 2023-08-14 06:41 UTC by Prabeshpd

- Close #1 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-15 08:06 UTC, tednguyendev commented on test/actions/user.test.ts
> +    const passowrdMatches = await crypt.compareWithHashValue(
I wonder if we should use `compareWithHashValue` here.

In this test file, I think we only need to test if we successfully created a user or not, as we already have tests for the function `hash`(and should also add test for the `compareWithHashValue` in `crypt.test.ts` as mentioned above).

2023-08-15 08:06 UTC, tednguyendev commented on test/actions/user.test.ts
> +  it('creates the user successfully', async () => {
I think we also need to test the case when create user fails.

2023-08-15 10:18 UTC, Prabeshpd commented on test/actions/user.test.ts
> +    const passowrdMatches = await crypt.compareWithHashValue(
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/18aa307b83b71eb7a4f07f1de9174e1d48936c4b

2023-08-15 10:18 UTC, Prabeshpd commented on test/actions/user.test.ts
> +    const passowrdMatches = await crypt.compareWithHashValue(
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/18aa307b83b71eb7a4f07f1de9174e1d48936c4b

2023-08-16 04:58 UTC, tednguyendev commented on test/actions/user.test.ts
> +  it('creates the user successfully', async () => {
How about:

```js
describe('given valid params', () => {
  it('creates the user successfully', async () => {

  });
});
```

2023-08-16 04:58 UTC, tednguyendev commented on test/actions/user.test.ts
> +  it('fails to create the user with same email', async () => {
How about:

```js
describe('given invalid params', () => {
  it('returns an internal server error', async () => {

  });
});
```

2023-08-16 04:58 UTC, tednguyendev commented on src/lib/crypt.test.ts
> +  describe('compare()', () => {
Should it be:
```js
  describe('compare()', () => {
```

Or this 👀 : 
```js
  describe('compareWithHashValue()', () => {
```

2023-08-16 04:58 UTC, tednguyendev commented on src/lib/crypt.test.ts
> +    it('does not matches a different string for the hash', async () => {
Same as above, how about:

```js
describe('given different string', () => {
  it('does not matches', async () => {

  });
});
```

2023-08-16 04:58 UTC, tednguyendev commented on src/lib/crypt.test.ts
> +    it('matches the same given string with hashed string', async () => {
And:

```js
describe('given same string', () => {
  it('matches', async () => {

  });
});
```

You can change the `it('matches')` into something more detailed, also 🙈

2023-08-16 05:25 UTC, olivierobert commented on src/app/actions/user.ts
> +    return { data: user, message: 'User is created successfully' };
How about a more user-friendly message:

```suggestion
    return { data: user, message: 'The user account has been created successfully' };
```

2023-08-16 05:25 UTC, olivierobert commented on src/app/actions/user.ts
> +      code: httpStatusCode.INTERNAL_SERVER_ERROR,
As raised previously, never raise 500 errors. That should be left for system and unhandled errors. It is best to return 422 / unprocessable entitye.

2023-08-16 05:25 UTC, olivierobert commented on src/lib/crypt.test.ts
>    });
It is best to add line breaks for readability between examples:

```suggestion
  });
  
```

2023-08-16 05:25 UTC, olivierobert commented on test/actions/user.test.ts
> +  });
Avoid over-using `before`/`after` blocks. It is best to keep all data/fixture generation in each test. It avoids creating dependencies between tests.

2023-08-16 05:25 UTC, olivierobert commented on test/actions/user.test.ts
> +    await dbClient.user.delete({ where: { email: 'dev@nimblehq.co' } });
How about just deleting all DB data after each test (to avoid having to put this in every test)?

2023-08-16 05:25 UTC, olivierobert commented on test/factories/searchResult.ts
> +  userId: 3,
Why does this need to be updated? Shouldn't this be created randomly and overridden in each test if necessary?

2023-08-16 06:30 UTC, Prabeshpd commented on test/actions/user.test.ts
> +    await dbClient.user.delete({ where: { email: 'dev@nimblehq.co' } });
In jest when trying to run sequentially it only runs the it section sequentially. The before and after blocks may run in parallel which causes problem for other test suite if I deleted all the data.

2023-08-16 07:10 UTC, Prabeshpd commented on test/actions/user.test.ts
> +  it('creates the user successfully', async () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/2036f663bcba82365ed0e5fc927d09baace2f2fe

2023-08-16 07:10 UTC, Prabeshpd commented on src/app/actions/user.ts
> +    return { data: user, message: 'User is created successfully' };
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/2036f663bcba82365ed0e5fc927d09baace2f2fe

2023-08-16 07:11 UTC, Prabeshpd commented on src/app/actions/user.ts
> +      code: httpStatusCode.INTERNAL_SERVER_ERROR,
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/2036f663bcba82365ed0e5fc927d09baace2f2fe

2023-08-16 07:11 UTC, Prabeshpd commented on test/factories/searchResult.ts
> +  userId: 3,
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/8b57db944cbf1198b9f74600182b22e0bf78206a

2023-08-16 07:13 UTC, Prabeshpd commented on test/actions/user.test.ts
> +    await dbClient.user.delete({ where: { email: 'dev@nimblehq.co' } });
I think it's better to have a script that populates all the required data for test. After the test has been completed then we can delete it as a teardown. At this point I think it's too much changes for it. May be we can have a separate task for it if it is a good idea

2023-08-16 08:28 UTC, tednguyendev commented on test/actions/user.test.ts
> +  it('creates the user successfully', async () => {
I don't understand the [new change](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/commit/2036f663bcba82365ed0e5fc927d09baace2f2fe#diff-049e1a145d794c53441e1070ca61c3baeb8656b13a59aed69e91094463f871d9R12) yet.

Why should we change `describe('User:')` to `describe('given valid Params')`? If you mean that our 2 examples both happen when the params are valid, then we can change it into:

```js
describe('User:', () => {
  describe('user email is unique', () => {
    it('creates the user successfully', async () => {
    });
  });

  describe('user email is NOT unique', () => {
    it('returns with unprocessable entity error', async () => {
    });
  });
});
```

And what does [this test](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/commit/2036f663bcba82365ed0e5fc927d09baace2f2fe#diff-049e1a145d794c53441e1070ca61c3baeb8656b13a59aed69e91094463f871d9R25) means? Why the name of it is `returns with unprocessable entity error`, but we `expect` it to not have the property `error.code` === `422`? 👀 

Thank you in advance!

2023-08-16 09:40 UTC, Prabeshpd commented on test/actions/user.test.ts
> +  it('creates the user successfully', async () => {
Oops. My bad I forgot to add the corrected test for it for checking the error.code. 🙈 Regarding the description updated the description of test in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/53a0b88ff7d76630b9ebcb25ddf54ab1c9463f74

2023-08-16 11:02 UTC, Prabeshpd commented on test/actions/user.test.ts
> +  it('creates the user successfully', async () => {
Yes, It's because in the previous test we have added an user. We are cleaning the database after all the test cases has passed.

2023-08-17 02:44 UTC, tednguyendev commented on test/actions/user.test.ts
> +  it('creates the user successfully', async () => {
I see. But in testing, I don't think tests should depend on each other. I see people prefer duplicating code than trying to DRY tests and then make it couple.

I think it will be better if we clean the database after each test, not after all tests. Cleaning the database after all tests indeed helps us create fewer database records(although for an IC like this, the database creations won't be even that much), but the trade-off is that it makes the tests depend on each other, like in this case, and it is a lot harder to both the others to maintain the tests or for the code reviewers to review.

Still, if you have reasons not to clear the database after each test, I suggest you at least still create 2 users with the same email on 1 test, not on 2 tests, like this:
```js
  describe('given email is not unique', () => {
    it('returns with unprocessable entity error', async () => {
      const userPayload1 = { name: user.name, email: 'dev1@nimblehq.co', password: user.password };
      await addUser(userPayload1);
      const userPayload2 = { name: user.name, email: 'dev1@nimblehq.co', password: user.password };

      await expect(addUser(userPayload2)).rejects.toHaveProperty('code', 422);
    });
  });
```

2023-08-17 03:06 UTC, Prabeshpd commented on test/actions/user.test.ts
> +  it('creates the user successfully', async () => {
It makes a lot sense to not to couple two testing scenarios. Thank you ted.

2023-08-17 03:09 UTC, Prabeshpd commented on test/actions/user.test.ts
> +  it('creates the user successfully', async () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/4d193cd0848c10680f0eacbda2771e7c976e4de6

2023-08-17 03:39 UTC, tednguyendev approved these changes

2023-08-17 05:56 UTC, olivierobert requested changes

2023-08-17 05:56 UTC, olivierobert commented on test/workers/scrape.test.ts
> +    userPayload = { ...user, id: 3 };
Shouldn't this use the constant defined above?

```suggestion
    userPayload = { ...user, id: userId };
```

This kind of complexity is why it is best not to use before block for creating fixtures. Prefer to move all of this logic to each test. There is come code repetitions but it is far easier to understand and maintain.

2023-08-17 05:56 UTC, olivierobert commented on test/actions/upload.test.ts
> +    userPayload = { ...user, id: 2 };
Why does this `id` needs to be equal to 2? That is odd. This tells me that there is something wrong in the test setup.

2023-08-17 05:56 UTC, olivierobert commented on test/actions/user.test.ts
> +    await dbClient.user.delete({ where: { email: 'dev@nimblehq.co' } });
I recommend fixing the test setup in this PR (or in a parallel PR that will be merged before this one) as many odd things are happening with id needing to be set to correct values 😵 

We could have something like https://flaviocopes.com/prisma-clear-database/ or https://medium.com/fuzzy-code/how-to-delete-all-the-table-contents-on-prisma-b99fff7ef7b

2023-08-17 06:51 UTC, Prabeshpd commented on test/actions/user.test.ts
> +    await dbClient.user.delete({ where: { email: 'dev@nimblehq.co' } });
Got your point. It seems that I was making the test more complicated than needed. I removed all the hardcoded values to faker generated once. 

Also, for deleting the table values the describe still runs them in parallel. So, if I delete all the fields in the search_result table. It affects my test on other test suite as it  deletes all of the data even the ones that is setup or created in that test suite.

I found a different solution to this problem. Jest has introduced `globalTeardown` option. It normally takes place after the test has been completed. Have been missing on this one options. I was normally using the mocha for backend related test which does not have this problem.

2023-08-17 06:53 UTC, Prabeshpd commented on test/workers/scrape.test.ts
> +    userPayload = { ...user, id: 3 };
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/6cc410ac2b91328f0e02761b613ac7e84945ddf1

2023-08-17 06:53 UTC, Prabeshpd commented on test/actions/upload.test.ts
> +    userPayload = { ...user, id: 2 };
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/6cc410ac2b91328f0e02761b613ac7e84945ddf1

2023-08-18 05:59 UTC, olivierobert requested changes
The test setup goes in the right direction, but there seems still to be dependencies between tests. So that must be resolved.

2023-08-18 05:59 UTC, olivierobert commented on test/database.integration.ts
I recommend moving this file to `test/support/database.ts` or `test/helpers/database.ts` as technically is part of the test tooling setup, so not on the same level as other tests.

2023-08-18 05:59 UTC, olivierobert commented on test/actions/upload.test.ts
> +    await dbClient.user.create({ data: user });
Where does the user object come from? 🤔 

Again, using before blocks causes more readability and dependency issues, so there are more downsides than benefits. One tricky part is [the order of execution](https://jestjs.io/docs/setup-teardown#order-of-execution). It is best to follow the team conventions to inline all test fixture creation into each test.

2023-08-18 05:59 UTC, olivierobert commented on test/actions/user.test.ts
> +      expect(createdUser.email).toEqual(user.email);
It is best to match passed values than rely on fake data when doing assertions when dealing with simple test data:

```
const userPayload = { name: user.name, email: 'dev@nimblehq.co', password: user.password };

expect(createdUser.email).toEqual('dev@nimblehq.co');
```

2023-08-18 05:59 UTC, olivierobert commented on test/actions/user.test.ts
> +      const userPayload = { name: user.name, email: 'dev1@nimblehq.co', password: user.password };
Why pass a specific email if no assertion is set against it?

2023-08-18 05:59 UTC, olivierobert commented on jest.integration.config.js
> +  globalTeardown: '<rootDir>/test/database.integration.ts',
While that works to reset the db after the whole test suite has been executed, it does not solve the issue of deleting data between each test. As a result, some test data can still corrupt other tests. So this would need to run `afterEach` in each test file.

2023-08-18 06:20 UTC, Prabeshpd commented on test/actions/user.test.ts
> +      const userPayload = { name: user.name, email: 'dev1@nimblehq.co', password: user.password };
Here, I am testing the logic of failure in case of creating the user with same email. So, in this test I am using the same email address to create the user twice. In the second creation I get the error. I am asserting for the error code here

2023-08-18 07:14 UTC, Prabeshpd commented on jest.integration.config.js
> +  globalTeardown: '<rootDir>/test/database.integration.ts',
The order of execution does not make sense for the promises. As they will be handled separately. Although the order of execution runs perfectly for the things that does not have promise.

2023-08-18 07:16 UTC, olivierobert commented on test/actions/user.test.ts
> +      const userPayload = { name: user.name, email: 'dev1@nimblehq.co', password: user.password };
Understood. That makes sense then :-) A minor improvement would be to use naming to give a hint:

```suggestion
      const userPayload = { name: user.name, email: 'unique.user@nimblehq.co', password: user.password };
```

It is a small trick that make tests more readable and maintainable.

2023-08-18 07:16 UTC, olivierobert commented on jest.integration.config.js
> +  globalTeardown: '<rootDir>/test/database.integration.ts',
I understand and that would be fine to keep as-is as long as there are no dependencies between each test. This is the most important issue to solve.

2023-08-18 07:27 UTC, Prabeshpd commented on test/database.integration.ts
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/956002a691762209a192135708b0bd8c1c2bbb48

2023-08-18 07:28 UTC, Prabeshpd commented on test/actions/upload.test.ts
> +    await dbClient.user.create({ data: user });
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/956002a691762209a192135708b0bd8c1c2bbb48

2023-08-18 07:28 UTC, Prabeshpd commented on test/actions/user.test.ts
> +      const userPayload = { name: user.name, email: 'dev1@nimblehq.co', password: user.password };
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/64/commits/956002a691762209a192135708b0bd8c1c2bbb48

2023-08-18 07:29 UTC, Prabeshpd commented on jest.integration.config.js
> +  globalTeardown: '<rootDir>/test/database.integration.ts',
I have removed the dependancy between the test as you suggested. Can you have a look at it please?

2023-08-21 03:00 UTC, olivierobert approved these changes

2023-08-21 03:00 UTC, olivierobert commented on test/factories/user.ts
> +  id: faker.number.int(10000),
There could be still some ID collisions but with the current test suite size, it should be sufficient.

2023-08-21 03:00 UTC, olivierobert commented on jest.integration.config.js
> +  globalTeardown: '<rootDir>/test/database.integration.ts',
That looks great. Let's keep this pattern for the upcoming tests.

2023-08-21 03:32 UTC, merged