[#68] [Chore] Extract classnames to scss attribute
nimblehq/ic-nextjs-prabesh-dahal pull request #69
Opened 2023-08-16 04:26 UTC by Prabeshpd

- Close #68 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-17 04:26 UTC, Prabeshpd commented on src/app/auth/login/page.tsx
> +      <h2 className="heading">Log In Form</h2>
use two words as per css conventions

2023-08-17 04:27 UTC, Prabeshpd commented on src/components/Login/Form.tsx
> +            <div className="button-container">
add form name to know where does it belong `login-form__button-container`. css convention compass

2023-08-17 06:24 UTC, olivierobert requested changes
This PR must be reworked entirely as it is a mix of correct and incorrect conventions 😵

2023-08-17 06:24 UTC, olivierobert commented on src/stylesheets/components/_login.scss
> +.login-form {
Use the UI element as a prefix (https://nimblehq.co/compass/development/code-conventions/css/#convention-25):

```suggestion
.form-login {
```

The file names must also match the CSS class name: `_form-login.scss`.

2023-08-17 06:24 UTC, olivierobert commented on src/stylesheets/components/_login.scss
> +  .form-container {
If you plan to follow the team conventions, then you need to follow all of them, such as BEM naming (https://nimblehq.co/compass/development/code-conventions/css/#convention-28).

2023-08-17 06:24 UTC, olivierobert commented on src/stylesheets/screens/_signup.scss
> +.signup-home {
Screen names could be composed of the route name `auth-signup` (from `auth/signup`)

2023-08-17 06:58 UTC, Prabeshpd reviewed
Converting this to draft. I was going through the CSS convention on compass. I need to change the scss definiton. Will rework on this and move it to sprint 5. cc @olivierobert @tednguyendev

2023-08-18 02:59 UTC, Prabeshpd commented on src/stylesheets/screens/_signup.scss
> +.signup-home {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/76b9a6970701fa88d693a0676b3834efac4cb14a

2023-08-18 03:00 UTC, Prabeshpd commented on src/stylesheets/components/_login.scss
> +  .form-container {
Fixed in latest changes.

2023-08-18 04:48 UTC, Prabeshpd reviewed
I am new to these SCSS conventions here.  I have tried to implement the conventions from compass as much as possible. I might have missed few although tried not to miss any 😅 . Please guide me in the right direction if I have missed any.

2023-08-18 06:21 UTC, olivierobert requested changes
I recommend you to check a previous codebase such as https://github.com/nimblehq/mia-web to see how the styles for layouts, screens, and components are set up.

2023-08-18 06:21 UTC, olivierobert commented on src/stylesheets/components/_form-signup.scss
Most of this file duplicates the code for `_form-login.scss`. Let's apply the DRY principle. In addition, changing the styles for one form should be applied to all forms, so by centralizing the styles it minimize work.

It would be best to create a file called `stylesheets/base/_form.scss` to define shared form styles:

```scss
.form {

}
```

Then use this class for the signup and sign-in forms.

2023-08-18 06:21 UTC, olivierobert commented on src/stylesheets/components/_form-login.scss
> +);
If that grid applies to all screens, it would be best to be defined in `stylesheets/_variables.scss`.

2023-08-18 06:21 UTC, olivierobert commented on src/stylesheets/components/_form-login.scss
> +    column-gap: 1.5rem;
Add a line break between styles and `@media` blocks:

```suggestion
    column-gap: 1.5rem;
    
```

2023-08-18 06:21 UTC, olivierobert commented on src/stylesheets/components/_form-login.scss
> +    }
Always place media blocks at the end of the styles to ensure proper cascading (so after line 45)

2023-08-18 06:21 UTC, olivierobert commented on src/stylesheets/screens/_auth-login.scss
Again there is code duplication between `auth-login.scss` and `auth-signup.scss` 😵 For shared layouts, create a file in `stylesheets/layouts/_auth.scss` and re-use it for both screens:

```scss
.layout-auth {

}
```

This class is usually set at the top-most HTML element: the `<html>` tag:

```html
<html class="layout-auth">
```

So the cascading structure should be: layouts (set on the html tag) > screens (set on the body class).

However, this would require too much rework for this PR in the current codebase. So this class could be applied to the `<main />` tag for now and reworked later.

2023-08-18 06:21 UTC, olivierobert commented on src/stylesheets/screens/_search-result.scss
> +    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono',
All font styles must be defined at the layout level to be shared by all screens

2023-08-18 08:38 UTC, Prabeshpd commented on src/stylesheets/components/_form-signup.scss
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/6ab1c2610a0b1125855608a6e80b18ec4bb800f2

2023-08-18 08:38 UTC, Prabeshpd commented on src/stylesheets/components/_form-login.scss
> +    column-gap: 1.5rem;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/6ab1c2610a0b1125855608a6e80b18ec4bb800f2

2023-08-18 08:38 UTC, Prabeshpd commented on src/stylesheets/components/_form-login.scss
> +    }
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/6ab1c2610a0b1125855608a6e80b18ec4bb800f2

2023-08-18 08:38 UTC, Prabeshpd commented on src/stylesheets/screens/_auth-login.scss
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/6ab1c2610a0b1125855608a6e80b18ec4bb800f2

2023-08-18 08:40 UTC, Prabeshpd commented
> I recommend you to check a previous codebase such as https://github.com/nimblehq/mia-web to see how the styles for layouts, screens, and components are set up.

Thank you Olivier. The link was super helpful to study about the scss conventions. SMACCS link in the compass also gave me a lot of insights on how to structure them. 🙂

2023-08-21 03:15 UTC, tednguyendev reviewed
The PR looks a lot better after the improvements 👍

2023-08-21 03:15 UTC, tednguyendev commented on src/stylesheets/base/_form.scss
> +  &__body {
On later PRs, you can use [Tailwind in CSS](https://www.wearecogworks.com/blog/how-to-use-tailwind-with-bem/) instead of having to style everything all over again in CSS like this 👍

2023-08-21 03:18 UTC, olivierobert requested changes

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/application.scss
> +@import 'components';
Components must be imported before screens so that they can be overridden on a per-screen basis:

```suggestion
@import 'base';

@import 'layouts/auth';
@import 'layouts/default';

@import 'components';

@import 'screens';
```

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/application.scss
> +// base
These comments do not add much value as the duplicates the file naming

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/application.scss
> +@import 'base/form';
How about creating an index file as done for components and screens? It looks inconsistent as-is.

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/base/_form.scss
> +  width: 100%;
Isn't it the default behavior? If yes, it can be removed. If not, explain why is is needed.

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/base/_form.scss
> +    @layer components {
Is the `@layer` needed? This new CSS spec aims to allow more control on the cascading order but since the component is defined with BEM, we might not need it:

```suggestion
    @apply shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600;
```

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/base/_form.scss
> +    column-gap: 1.5rem;
Minor preference to group related properties together for readability:

```
    display: grid;
    row-gap: 2rem; -> relates to grid
    column-gap: 1.5rem; -> relates to grid

    margin-top: 2.5rem; -> does not relate to grid
```

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/base/_form.scss
> +    color: #111827;
That should be defined in a variable to avoid repeating it

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/base/_form.scss
> +      width: 0px;
Why is a 0 border needed if the border-radius is set?

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/base/_form.scss
> +  &__button--submit {
There are some shared styles between buttons so prefer doing:

```css
&__button {
   // shared styles

   &--reset {
     // specific styles for this button style
   }

   &--submit {
     // specific styles for this button style
   }
}
```

2023-08-21 03:18 UTC, olivierobert commented on src/stylesheets/screens/_home-page.scss
> +  &__body {
That could be defined at the layout level, no?

2023-08-21 03:18 UTC, olivierobert commented on src/app/page.tsx
> +    <main className="home-page">
It is missing the usage of `layout-default` or please point where this is used? The idea is to have the following structure:

```
- layout container
  - screen container
    - page content    
```

2023-08-21 05:09 UTC, Prabeshpd commented on src/stylesheets/base/_form.scss
> +  width: 100%;
It is not default behaviour. The `formik` wrapper is not taking the full-width of the container so to take full width of container. It is added

2023-08-21 05:10 UTC, Prabeshpd commented on src/stylesheets/base/_form.scss
> +    @layer components {
To use the tailwind apply utility  it is added. If directly the apply utils is added it is generating error. On the documentation of tailwind to it is recommended to use the apply util with wrap of layer components.

2023-08-21 07:21 UTC, Prabeshpd commented on src/stylesheets/base/_form.scss
> +    text-decoration-color: #111827;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/f82eebe36a10f7bf2904f73d90fede8db913bc79

2023-08-21 07:21 UTC, Prabeshpd commented on src/stylesheets/application.scss
> +// base
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/f82eebe36a10f7bf2904f73d90fede8db913bc79

2023-08-21 07:21 UTC, Prabeshpd commented on src/stylesheets/base/_form.scss
> +    color: #111827;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/f82eebe36a10f7bf2904f73d90fede8db913bc79

2023-08-21 07:21 UTC, Prabeshpd commented on src/stylesheets/base/_form.scss
> +      width: 0px;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/f82eebe36a10f7bf2904f73d90fede8db913bc79

2023-08-21 07:21 UTC, Prabeshpd commented on src/stylesheets/base/_form.scss
> +  &__button--submit {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/69/commits/f82eebe36a10f7bf2904f73d90fede8db913bc79

2023-08-22 02:43 UTC, tednguyendev approved these changes

2023-08-22 04:48 UTC, olivierobert commented on src/stylesheets/base/_form.scss
> +    @layer components {
Understood 👍

2023-08-22 04:50 UTC, olivierobert approved these changes

2023-08-22 04:54 UTC, merged