[#13] [Backend] As a user, I can view the list of search results
nimblehq/ic-nextjs-prabesh-dahal pull request #75
Opened 2023-08-22 07:06 UTC by Prabeshpd

- Close #13 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-22 09:55 UTC, tednguyendev commented on test/services/searchResultEntity.test.ts
> +      const createdUser = await createUser(user);
Why do you need to create the `userFabricator`?

Even when we need to create a user with a custom email, I think we can reuse the existing `user` factory:

```js
const createdUser = await createUser({ ...user, email: 'abc@gmail.com' });
```

And we don't need to create a user with a custom email here, so using `user` may be more suitable.

2023-08-22 09:55 UTC, tednguyendev commented on src/app/actions/searchResult.ts
> +export async function listResults(
Why don't you name the function name(`listResults`) and the file name(`searchResult`) the same for more consistency? 👀 

Is that a JS convention? 🤔

For the [upload action](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/blob/develop/src/app/actions/upload.ts), I saw you named the file and the function name differently too(`upload.ts` + function `uploadCsv`)

2023-08-22 09:55 UTC, tednguyendev commented on src/queries/searchResultQuery.ts
> +class SearchResultQuery {
Correct me if I'm wrong, but the purpose of this whole class is just to create a hash, right? 🙈 

How about using something simpler, like, a function?

```js
function getQuery(params) {
  const query = {}

  if (params.userId) {
    query['userId'] = params.userId;
  }

  if (params.keyword) {
    query['keyword'] = { contains: params.keyword };
  }

  return query
}
```

2023-08-22 09:55 UTC, tednguyendev commented on src/services/searchResultEntity.ts
> +    const searchResultQuery = new SearchResultQuery(authenticatedQueryFilterParams);
Continue with the comment above. And instead of using this class as:

```js
const searchResultQuery = new SearchResultQuery(authenticatedQueryFilterParams);
const query = searchResultQuery.construct();
```

We can just:
```js
const searchResultQuery = getQuery(authenticatedQueryFilterParams);
```

2023-08-22 09:55 UTC, tednguyendev commented on src/services/searchResultEntity.ts
> +    const { currentPage = 1 } = querySearchWithPaginationParams;
This snippet is a bit painful to read 🤣

The variable names are just so long:
- `authenticatedQueryFilterParams`
- `getPaginationParams(querySearchWithPaginationParams)` 

Remind me of Java's method names 🙈

2023-08-22 09:55 UTC, tednguyendev commented on src/app/actions/searchResult.ts
> +  querySearchWithPaginationParams: QuerySearchWithPaginationParams<{
Why do we call it `querySearchWithPaginationParams` instead of something like, `params`? 👀 Is that a convention?

2023-08-22 09:55 UTC, tednguyendev commented on src/repositories/searchResult.test.ts
> +  describe('update Search Result', () => {
```suggestion
  describe('Update Search Result', () => {
```

2023-08-22 09:55 UTC, tednguyendev commented on src/repositories/searchResult.test.ts
> +  describe('update Search Result', () => {
Plus, this [`describe('createSearchResult', () => {`](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/blob/develop/src/repositories/searchResult.test.ts#L6)

Should be fixed too: 

```js
  describe('Create Search Result', () => {
```

2023-08-22 09:55 UTC, tednguyendev commented on test/services/searchResultEntity.test.ts
> +  describe('given valid filter pagination params and user id', () => {
```suggestion
  describe('given valid filter pagination params and userId', () => {
```

2023-08-22 09:55 UTC, tednguyendev commented on test/services/searchResultEntity.test.ts
> +describe('listSearch', () => {
The structure of your test has room for improvement 👀 

Instead of:

```js
describe('given valid filter pagination params and user id', () => {
  it('returns the valid data after filter', async () => {
  });
});

describe('given userId with no search results associated with user', () => {
  it('returns empty data', async () => {
  });
});

describe('given only pagination params', () => {
  it('returns all the data with pagination', async () => {
  });
});
```

How about:

```js
describe('given ONLY paginate', () => {
  it('returns correct response', async () => {
  });
});

describe('given paginate AND search', () => {
  describe('given user have search results', () => {
    it('returns correct response', async () => {
    });
  });

  describe('given user NOT have search results', () => {
    it('returns correct response', async () => {
    });
  });
});
```

2023-08-22 10:01 UTC, tednguyendev commented on src/queries/searchResultQuery.ts
> +class SearchResultQuery {
Same as above, we are having tests for lib files.

2023-08-22 10:08 UTC, Prabeshpd commented on src/app/actions/searchResult.ts
> +export async function listResults(
No actually I want to have all the functions of searchResult entity or table here. so, that's why the file name and function name are different. If it was the default function of file would have the same function name as that of file.

2023-08-22 10:09 UTC, Prabeshpd commented on src/queries/searchResultQuery.ts
> +class SearchResultQuery {
Yes, In future there will be other parameters too. So, ended up creating class. In the future the function would be too big with many if conditions. Just wanted to avoid it.

2023-08-22 10:11 UTC, Prabeshpd commented on src/app/actions/searchResult.ts
> +  querySearchWithPaginationParams: QuerySearchWithPaginationParams<{
Just wanted to make it more meaningful with the contents that it has. Seems I have created quite a long name. Will try to come up with meaningful short name or replace it with `query`.

2023-08-22 10:24 UTC, tednguyendev commented on src/queries/searchResultQuery.ts
> +class SearchResultQuery {
I wonder how many more params will we have that we need to use a class 🤔

But yes, that will work, too ✋ It's just that I prefer keeping things simple. And for a function with the purpose is to just transforming params, normally, I will try to delay making it a class as long as I can 😄

2023-08-23 04:11 UTC, olivierobert requested changes
Many implementation issues so you will need to revise the implementation entirely

2023-08-23 04:11 UTC, olivierobert commented on src/repositories/searchResult.ts
> +export const listAllPendingSearchResult = async (userId: number) =>
How about making it more generic (so that it can handle any status and setting a default):

```suggestion
export const listSearchResultByStatus = async (userId: number, status: string = SearchResultStatus.PENDING) =>
```

2023-08-23 04:11 UTC, olivierobert commented on src/types/query.ts
SHouldn't this be called `pagination.ts` instead as it mostly related to that topic 🤔 ?

2023-08-23 04:11 UTC, olivierobert commented on src/repositories/searchResult.ts
> +    take: paginationParams.limit,
How about having default values so that we don't need to pass them all the time? The defaults should be set as constant or env variables.

2023-08-23 04:11 UTC, olivierobert commented on test/factories/searchResult.ts
> +export const searchResultFabricator = (userId?: number, keyword?: string) => ({
Why is a new factory needed? The existing one can be used

2023-08-23 04:11 UTC, olivierobert commented on src/queries/searchResultQuery.ts
> +  construct() {
That is an odd name since it is very close to `constructor` 💣  How about simply:

```suggestion
  build() {
```

2023-08-23 04:11 UTC, olivierobert commented on src/queries/searchResultQuery.ts
That object does not do any querying 😅 It is more like a helper in its current state. I am unsure if it has more value than just using the exiting repository object 🤔

2023-08-23 04:11 UTC, olivierobert commented on src/queries/searchResultQuery.ts
> +    if (this.queryParams.userId) {
Prefer the early return syntax:

```javascript
filterByUserId() {
  const userId = this.queryParams.userId;

  if (!tuserId) return;

  this.searchResultQuery['userId'] = userId;
}
```

2023-08-23 04:11 UTC, olivierobert commented on src/queries/searchResultQuery.ts
> +  filterByUserId() {
How about making these classes private:

```suggestion
  #filterByUserId() {
```

Or just using the standard prefix `_` to explicitly tell that these methods should not be accessed:

```suggestion
  _filterByUserId() {
```

2023-08-23 04:31 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
I am a little confused on this one. I understood your point on making a query object and creating the searchResultQuery from it. So, as I understand I can create searchQuery object and call the repository to fetch the data from the actions page handler itself right? 
The problem is same piece of code is utilised in API as well. I wanted to disintegrate the logic of formatting data or raising some custom errors for end response or result. Normally I used to put this in service layer in my previous projects. If I want to decouple the logic then for such scenarios where should I put them instead of service layer? Can you guide me on this part please?

2023-08-23 05:48 UTC, olivierobert commented on src/services/searchResultEntity.ts
As its name says, a query object is meant to abstract complex DB querying logic. This is usually used in controllers to keep them lean. However, in the current implementation, the query object does not do any DB query but is merely a helper.

As per [my comment raised below](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/75#discussion_r1302459448), an option is to use the existing repository: add params for pagination with default values and perform the DB query. The output should be a list of records, so not structured as an API response:

```
data: searchResults,
meta: { totalCounts: totalSearchResults, currentPage, limit: paginationQueryParams.limit },
```

This response structure is only needed for the API response. On a regular Web controller, we would need two props: 1) search results and 1) pagination (current page, total pages, current page size) Treats this two props as distinct items.

2023-08-23 06:26 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
Okay. Got the point. Thank you. Will correct the PR.

2023-08-24 04:18 UTC, Prabeshpd commented on src/repositories/searchResult.ts
> +    take: paginationParams.limit,
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/75/commits/8dbebf789e17df5f983c903fad85b20f56d1c482

2023-08-24 04:18 UTC, Prabeshpd commented on src/repositories/searchResult.ts
> +export const listAllPendingSearchResult = async (userId: number) =>
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/75/commits/8dbebf789e17df5f983c903fad85b20f56d1c482

2023-08-24 04:31 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
I have removed the function from the service layer. Apart from that I have disintegrated the web controller to two distinct actions to get the count and results. I have transformed the helper query builder to function and moved it to lib folder. I believe it is much simpler this way. If the needs arises then we can convert this to query object and use it to query the database. For this use case I think this is extra work. Can you have a look at it please? cc @olivierobert , @tednguyendev

2023-08-24 05:35 UTC, tednguyendev approved these changes
Just some minors.

This PR is a lot more readable now 👍

2023-08-24 05:35 UTC, tednguyendev commented on test/repository/searchResult.test.ts
> +    describe('given user have no search Result', () => {
```suggestion
    describe('given user have no search results', () => {
```

As you are already using the world "results" instead of "Result" [above](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/75/files#diff-ecc7ec255649de569928eaa447a954face611cedeaf5d9f51bd987b921e5b5deR59).

2023-08-24 05:35 UTC, tednguyendev commented on test/repository/searchResult.test.ts
> +    it('returns all the data with pagination.', async () => {
```suggestion
    it('returns all the data with pagination', async () => {
```

(Remove the dot)

2023-08-24 05:35 UTC, tednguyendev commented on src/lib/searchResultQuery.ts
> +  return query;
Looks a lot neater! 😄

2023-08-24 05:35 UTC, tednguyendev commented on src/lib/pagination.test.ts
> +    it('returns default pagination query parameters', () => {
The test structure is improving 💪

2023-08-24 06:59 UTC, tednguyendev approved these changes
LGTM now 👍

2023-08-25 04:00 UTC, olivierobert requested changes

2023-08-25 04:00 UTC, olivierobert commented on test/repository/searchResult.test.ts
Why are these tests not in `repositories/searchResult.test.ts`? I would be best to have all tests for the same file together.

2023-08-25 04:15 UTC, Prabeshpd commented on src/lib/searchResultQuery.test.ts
> +      expect(query).toEqual({ userId: 1 });
It doesnot actually query the database. It is a helper. It is only testing whether the resulting object from helper function is in place. I think it will be much clearer if I assert the resulting query does not have userId with value 2 or other prperties.

2023-08-25 04:16 UTC, Prabeshpd commented on test/repository/searchResult.test.ts
These are unit tests. These test are mocking the database implementation. The other are integration test that interact with database and need separate database instance. I personally prefer the integration testing for such scenarios. I see here the mocking is done and tested in the js-framework that's why kept them.

2023-08-25 04:19 UTC, Prabeshpd commented on src/lib/searchResultQuery.test.ts
> +    it('returns query containing userId', () => {
List search result would actually return the data after pagination. So, it does not have information on exactly how much data is present in the database. Should I return the count from the action function as well. Since, last time you suggest to treat them as two separate props for presentation layer. I used separate function. I can merge them to one action. U think that makes way more sense.

2023-08-25 04:21 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
List search result would actually return the data after pagination. So, it does not have information on exactly how much data is present in the database. Should I return the count from the action function as well. Since, last time you suggest to treat them as two separate props for presentation layer. I used separate function. I can merge them to one action. U think that makes way more sense.

2023-08-25 06:00 UTC, Prabeshpd commented on src/lib/searchResultQuery.test.ts
> +    it('returns query containing userId', () => {
It is only a helper function to return the query. 😅. I think right now it will be complicated to make the query object to query the database. In the further filter process when there is need I plan to create the query object to filter lists.

2023-08-25 06:22 UTC, olivierobert commented on src/services/searchResultEntity.ts
Let's clarify why we need a total count of search results  😅  What is the purpose? It seems to be for setting meta data (https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/files#diff-082b2577a87e52b1266cce36139a4a71c7275509b6e8937ee29d9e93e35f22dcR46) but I am unsure how it is used 🤔 

What I mean is that it seems redundant to have a server action to do a count as one could use the existing server action (without any pagination) and do a count on the client side.

2023-08-25 06:22 UTC, olivierobert commented on src/lib/searchResultQuery.test.ts
> +    it('returns query containing userId', () => {
Indeed. I get it now :-)

2023-08-25 06:25 UTC, olivierobert commented on test/repository/searchResult.test.ts
The team does not draw a difference between unit and integration testing. All of them are considered non-UI tests. I recommend you to reach https://nimblehq.co/compass/development/testing/#test-pyramid and check this presentation: https://docs.google.com/presentation/d/1cM_VHVYHSw7WLMy9XRpqtWc5NIkBlifdcAyJ4gCioVg/edit?usp=sharing

So there is no need to separate these tests to a separate file. If a DB must be used for specific tests to have more confidence, if no don't.

2023-08-25 06:26 UTC, olivierobert commented on src/lib/searchResultQuery.test.ts
> +      expect(query).toEqual({ userId: 1 });
Same concern as above so all is good

2023-08-25 06:29 UTC, Prabeshpd commented on test/repository/searchResult.test.ts
Ok. makes more sense. the test with mocked database don't add much value. Will change those to use database instance. I think it's better to do those in separate task.

2023-08-25 06:33 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
To handle the pagination we would need to know how many data are present totally in database. So, the fetch of results first will give the user 10 sets of data. So, the count the frontend has is total of 10 length. But in database there are lots of data. so, to know how many pages of data are there we would need the count of total data based on filters excluding pagination. So, I would normally get the query and return from the same function that is returning the total count of data. 😅  For, now I will be returning them from the one single action and update the PR.

2023-08-25 06:39 UTC, Prabeshpd commented on test/repository/searchResult.test.ts
I really liked the presentation. 😄  I saw lot of mockings in js-framework repo so followed that one. Will update my few test cases to add more value. Thank you

2023-08-25 06:48 UTC, Prabeshpd commented on src/constants/constants.ts
> +export const DEFAULT_CURRENT_PAGE = 1;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/75/commits/77ad23529ead354c06bec249a7d91a3de103567d

2023-08-25 06:48 UTC, Prabeshpd commented on src/lib/searchResultQuery.ts
> +  if (params.keyword) {
Ok.

2023-08-25 06:56 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
I have updated my code. Can you have a look at it please?

2023-08-25 08:13 UTC, olivierobert commented on src/services/searchResultEntity.ts
I fully understood the concern about having paginated results not being compatible with the need to have a total count. That is not the issue. What I mean it is redundant to have two fetch methods. We could count the total results by just using `listSearchResult`. 

All attributes are optional in `searchResultQueryListParams`:

```typescript
export interface searchResultQueryListParams {
  customQuery?: { [key: string]: any };
  paginationQuery?: PaginationQueryParams;
}
```

So `listSearchResult` could recent no `paginationQuery` if necessary (which is the same as what `countSearchResult` operates).

To make that happen `listSearchResult` could need to be modified:

```typescript
export const listSearchResult = async (query: searchResultQueryListParams = {}, isPaginated:bool = true) => {
  const { customQuery, paginationQuery } = query;

  return dbClient.searchResult.findMany({
    where: customQuery,
    skip: paginationQuery?.offset || PAGINATION_OFFSET_ROWS,
    take: paginationQuery?.limit || PAGINATION_LIMIT,
  });
};
```

So the code could be:

```typescript
const searchResults = await listSearchResult({
  customQuery,
  paginationQuery,
});
const count = await listSearchResult(customQuery, false).length
```

The current approach works but I wanted to raise a different alternative 💡

2023-08-25 08:19 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
Ok. Understood your point. Just a little concern here. Doesn't it make the function to look a little weird and unreadable to add boolean as the argument. I generally tend to avoid these arguments. Just wanted to know are these good patterns to have or not?

2023-08-25 08:22 UTC, Prabeshpd commented on test/repository/searchResult.test.ts
For those tests there are two separate configs. If I move these tests then I would need to add the setup of data related to database. As the current test structure as unit config and integration config. The unit config mocks the prisma implementation completely and they look into folder for which configuration to use. If I move them to test folder they will follow the test with real database. Will it be okay if I did in the new pR creating new task?

2023-08-28 03:40 UTC, olivierobert commented on src/services/searchResultEntity.ts
By weirdness, (I assume that) you mean that it could be hard to understand what this option is for without looking at the implementation. That could be improved in several ways:

- Passing an object for options:

```
export interface searchQueryListOption {
  isPaginated: bool;
}

const defaultSearchQueryListOption: searchQueryListOption = {
    isPaginated: true,
};

export const listSearchResult = async (query: searchResultQueryListParams = {}, option = defaultSearchQueryListOption) => {
  const { customQuery, paginationQuery } = query;

 //...
};
```

To me this is less weird that duplicating the code to fetch all search details 😅

2023-08-28 06:33 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
I have implemented these changes. I tried decorator but I think it is too complex for now. So, moved to solution of yours. 😅 . I got you point and it makes a lot sense too. Thank you. Can you have a look at it now?

2023-08-28 07:53 UTC, olivierobert reviewed
Just a minor suggestion to consider. It is not compulsory so up to you to decide.

2023-08-28 07:53 UTC, olivierobert commented on src/repositories/searchResult.ts
> +  return dbClient.searchResult.findMany({ where: customQuery });
Minor sugegstion: repetitions for `{ where: customQuery }` can be avoided with:

```javascript
let findQuery = { where: customQuery };

if (options.isPaginated) {
  findQuery = {...findQuery, {
      skip: paginationQuery?.offset || PAGINATION_OFFSET_ROWS,
      take: paginationQuery?.limit || PAGINATION_LIMIT,
  }};
}

return dbClient.searchResult.findMany(findQuery);
```

2023-08-28 07:54 UTC, olivierobert approved these changes

2023-08-28 08:02 UTC, merged