[#73] [Backend] As a user, I can view the detail of single keyword
nimblehq/ic-nextjs-prabesh-dahal pull request #78
Opened 2023-08-22 09:53 UTC by Prabeshpd

- Close #73 

## What happened 👀

-  Create a feature to fetch detail of keyword
-  Add test

## Insight 📝

Add a function to fetch the detail of keyword. The function is authenticated and if the userId of the search result does not match with the current user Id an `Unauthorised` error is thrown. 

## Proof Of Work 📹

Passed CI pipelines test

2023-08-23 09:40 UTC, tednguyendev reviewed
Just minor things 🐜

2023-08-23 09:40 UTC, tednguyendev commented on test/services/searchResultEntity.test.ts
> +      const createdSearchResult = await createSearchResult(searchResultPayload);
What is the purpose of the function `createSearchResult`? Why did we create it in this PR? 🤔

2023-08-23 09:40 UTC, tednguyendev commented on test/services/searchResultEntity.test.ts
> +  describe('given valid id and user id associated with result', () => {
This structure can also be benefited from the reorganization like in [the previous PR](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/75#discussion_r1301393236) 👀

2023-08-23 09:40 UTC, tednguyendev commented on src/services/searchResultEntity.ts
> +    console.log(err);
Friendly reminder to remove the loggings 👍

2023-08-23 09:40 UTC, tednguyendev commented on src/repositories/searchResult.ts
> +export const findById = async (id: string) => dbClient.searchResult.findUnique({ where: { id } });
We should also have test for this new function ✋

2023-08-23 09:40 UTC, tednguyendev commented on test/services/searchResultEntity.test.ts
> +      await expect(findById(faker.string.uuid(), createdUser.id)).rejects.toHaveProperty(
I think we don't need to use `faker` here, as we don't need this to be "realistic" , right?

2023-08-24 05:14 UTC, Prabeshpd commented on src/repositories/searchResult.ts
> +export const findById = async (id: string) => dbClient.searchResult.findUnique({ where: { id } });
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/78/commits/fbcf9f0cfb59da29becc014190b78bb67ef4aa64

2023-08-24 05:14 UTC, Prabeshpd commented on test/services/searchResultEntity.test.ts
> +  describe('given valid id and user id associated with result', () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/78/commits/fbcf9f0cfb59da29becc014190b78bb67ef4aa64

2023-08-24 05:14 UTC, Prabeshpd commented on test/services/searchResultEntity.test.ts
> +      await expect(findById(faker.string.uuid(), createdUser.id)).rejects.toHaveProperty(
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/78/commits/fbcf9f0cfb59da29becc014190b78bb67ef4aa64

2023-08-24 05:16 UTC, Prabeshpd reviewed
I have added the fetch By Id to service file. Since, it has some custom errors to be raised. Is it okay to place it here? cc @olivierobert @tednguyendev

2023-08-24 06:15 UTC, tednguyendev reviewed
Another batch of minor things 🐜

2023-08-24 06:15 UTC, tednguyendev commented on src/services/searchResultEntity.ts
> +  if (searchResult.userId !== userId) {
Just minor: You can also use [Prisma's findMany](https://www.prisma.io/docs/concepts/components/prisma-client/crud#get-all-records), which will also allow you to pass the user.id to the query and we will be able to check both things(the newsletter id exists, and the user of the newsletter is the current user) 👀

An example: [Link](https://github.com/nimblehq/js-framework-benchmark/pull/126#discussion_r1228936098)

2023-08-24 06:15 UTC, tednguyendev commented on src/queries/searchResultQuery.ts
> +class SearchResultQuery {
This seems to conflict with the [the `getSearchResultQuery`](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/75/files#diff-90974662337520441e2025fcc59f378da40274248e5deb52452910029b78c41dR11)

2023-08-24 06:15 UTC, tednguyendev commented on test/services/searchResultEntity.test.ts
> +            id: 'cb77e671-2447-4197-897d-540bc114df48',
I see we are using this `id` at many places. Maybe we should assign it to a variable ✋

2023-08-24 06:42 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
> +  if (searchResult.userId !== userId) {
But doesn't it hides the fact that whether the user is `unauthorized` to view the result or the result does not exist entirely on the record (like deleted).

2023-08-24 06:57 UTC, tednguyendev commented on src/services/searchResultEntity.ts
> +  if (searchResult.userId !== userId) {
Oh yes. We can not differentiate the 2 errors if we do it that way.

But since the logic of our application is that a user can only see his keywords, if one user is trying to view another user's keyword, I don't think it matters if we show what error to him, since he is trying to do the wrong, to access another person's data. We just need to prevent him.

Plus, if he wants to access the keyword of id `123`, and that's not his keyword, I still think it is also acceptable for the application to show the error "This keyword does not exist (to him)".

What do you think about this? 🤔

2023-08-24 10:56 UTC, tednguyendev commented on test/services/searchResultEntity.test.ts
> +  describe('given valid id', () => {
How about give the code a little space to breath 🌊

```suggestion
  const defaultUUID = 'cb77e671-2447-4197-897d-540bc114df48';
  
  describe('given valid id', () => {
```

2023-08-25 07:09 UTC, Prabeshpd commented on test/services/searchResultEntity.test.ts
> +  describe('given valid id', () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/78/commits/e56350f43b948ee59561e6d3b21aed7291338acd

2023-08-25 07:10 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
> +  if (searchResult.userId !== userId) {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/78/commits/e56350f43b948ee59561e6d3b21aed7291338acd

2023-08-25 07:24 UTC, tednguyendev approved these changes

2023-08-25 07:24 UTC, tednguyendev commented on src/services/searchResultEntity.ts
> +      message: 'Unauthorized to view the keyword detail.',
I think [what I meant](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/78#discussion_r1303886074) is that I'm more of an advocate for the 'Keyword detail can not be found.' if we can only choose 1 message to show 🤣 Do you find this 'Unauthorized' message more suitable? 🤔 

Anyway, I will approve this PR first so it does not block you ✋

2023-08-25 07:26 UTC, Prabeshpd commented on src/services/searchResultEntity.ts
> +      message: 'Unauthorized to view the keyword detail.',
Got your point. Will update the message. 😅

2023-08-28 03:48 UTC, olivierobert requested changes

2023-08-28 03:48 UTC, olivierobert commented on src/app/actions/searchResult.ts
> +      }
This implementation is inconsistent with the method above. There is no extra logic to throw an exception in `listSearchResults`. Couldn't this be handled with:

```
code: error.code || httpStatusCode.UNPROCESSABLE_ENTITY,
```

2023-08-28 03:48 UTC, olivierobert commented on src/app/actions/searchResult.ts
> +        code: httpStatusCode.UNPROCESSABLE_ENTITY,
If a record cannot be fetched, then the error should always be 404 regardless of the error. Same as for `listSearchResults` too (this was missed before).

2023-08-28 03:48 UTC, olivierobert commented on src/repositories/searchResult.ts
> +export const createMultipleSearchResults = async (
How about being consistent with Prisma naming:

```suggestion
export const createManySearchResults = async (
```

2023-08-28 04:24 UTC, Prabeshpd commented on src/repositories/searchResult.ts
> +export const createMultipleSearchResults = async (
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/78/commits/bd13796cf9665b67851e198390d976e544820185

2023-08-28 04:25 UTC, Prabeshpd commented on src/app/actions/searchResult.ts
> +      }
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/78/commits/ae63f9e8929978366a265fa00237061d9e3391c5

2023-08-28 04:25 UTC, Prabeshpd commented on src/app/actions/searchResult.ts
> +        code: httpStatusCode.UNPROCESSABLE_ENTITY,
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/78/commits/ae63f9e8929978366a265fa00237061d9e3391c5

2023-08-28 07:54 UTC, olivierobert approved these changes

2023-08-28 08:03 UTC, merged