[#79] [UI] Setup auth for frontend
nimblehq/ic-nextjs-prabesh-dahal pull request #80
Opened 2023-08-23 14:55 UTC by Prabeshpd

- Close #79 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-24 08:07 UTC, Prabeshpd commented
> The log out button is cropped out of the demo video 🤣

oh 😆 Will make another video. 😅

2023-08-25 06:58 UTC, Prabeshpd commented on src/stylesheets/_variables.scss
> +$color-white: #ffffff;
I have segregated this in another PR.

2023-08-25 07:14 UTC, Prabeshpd commented on src/components/Header/Header.test.tsx
> +    it('adds active property to class name', async () => {
I think it is redundant but I believe there should not be inactive the default should be inactive. I will correct this behaviour in code

2023-08-25 07:20 UTC, Prabeshpd commented on src/components/Header/Header.test.tsx
> +    it('renders Header component', async () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/80/commits/2260dfb34f5107f4354216eb631f897aeee6594e

2023-08-25 07:20 UTC, Prabeshpd commented on src/components/Header/Header.test.tsx
> +    it('adds active property to class name', async () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/80/commits/2260dfb34f5107f4354216eb631f897aeee6594e

2023-08-25 07:20 UTC, Prabeshpd commented on src/app/(app)/page.tsx
> +    fetchCurrentUserAction().then((currentUser) => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/80/commits/2260dfb34f5107f4354216eb631f897aeee6594e

2023-08-25 08:39 UTC, tednguyendev commented on src/components/Header/Header.test.tsx
> +    it('renders Header component', async () => {
What I means is to remove the `describe` since it is kind of redundant here ✋

2023-08-25 08:41 UTC, tednguyendev commented on src/components/Header/Header.test.tsx
> +    it('renders Header component', async () => {
But I will approve this PR still since this is minor 👍

2023-08-25 08:41 UTC, tednguyendev approved these changes

2023-08-28 04:05 UTC, olivierobert requested changes

2023-08-28 04:05 UTC, olivierobert commented on src/components/Header/Header.tsx
> +              segment === null ? 'feature/ui-authorization--active' : ''
1. Why is that class "feature/ui-authorization--active" needed? This seems temporary as it corresponds to the branch name 🤔 What is the plan there?
2. For conditional classes, how about using the null coalescing operator:

```
segment ?? 'class-name'
```

Or https://www.npmjs.com/package/classnames can be used

2023-08-28 04:05 UTC, olivierobert commented on src/stylesheets/components/_app-header.scss
> +    &--left {
Avoid using positioning in the class names as these can change depending on the screen size and over time. This is also not a modifier (for a variant) for a sub-element of the navigation. ALso avoid nexting more than 3 levels down.

The CSS structure should be:

```
.app-header {
  &__navigation {}

  &__menu { // what is called app-header__navigation--left}

  &__dropdown { // what is called app-header__navigation--right }
}
```

2023-08-28 04:36 UTC, Prabeshpd commented on src/stylesheets/components/_app-header.scss
> +    &--left {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/80/commits/c6f6923d7ed4f4043bbf6e019666df6214522fa2

2023-08-28 04:36 UTC, Prabeshpd commented on src/components/Header/Header.tsx
> +              segment === null ? 'feature/ui-authorization--active' : ''
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/80/commits/c6f6923d7ed4f4043bbf6e019666df6214522fa2

2023-08-28 07:58 UTC, olivierobert requested changes

2023-08-28 07:58 UTC, olivierobert commented on src/components/Header/Header.tsx
> +            className={classNames('app-header__brand', {
`-brand is usually for the logo Since it is a menu item it could be:

```suggestion
            className={classNames('app-header__menu-item', {
```

or simply:

```suggestion
            className={classNames('app-header__link', {
```

I missed that in the first review 🙇

2023-08-28 07:58 UTC, olivierobert commented on src/stylesheets/components/_app-header.scss
> +  background-color: #1f2937;
That should be defined in `_variakles`. Avoid hard-coding any color or font values to ensure the UI is consistent.

2023-08-28 08:09 UTC, Prabeshpd commented on src/components/Header/Header.tsx
> +            className={classNames('app-header__brand', {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/80/commits/702ee846f6f726d9978aaa81f06aa9da4a3aea7c

2023-08-29 03:15 UTC, olivierobert approved these changes

2023-08-29 03:36 UTC, merged