[#15] [UI] As a user, I can view the list of search results
nimblehq/ic-nextjs-prabesh-dahal pull request #81
Opened 2023-08-23 15:00 UTC by Prabeshpd

- Close #15 

## What happened 👀

- Created a component for listing search results with a search feature.
- Created a custom pagination component.
- Add testing
- Add styling
- Add relevant columns for tables

## Insight 📝

A page was created for listing the search results. Custom pagination was created leveraging react hooks. Search feature was added to the table using debouncing to search.

## Proof Of Work 📹

https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/39412015/3125405b-a313-44d3-a915-b994804bfc8e

2023-08-25 06:38 UTC, tednguyendev reviewed
Mostly naming issues

2023-08-25 06:38 UTC, tednguyendev commented on src/components/SearchResultList/SearchResultList.tsx
> +              <th className="table__head-column">Position</th>
Tbh, this table head, along with its column bodies(`React Developer`) is kind of confusing since we are searching `keywords` 😭 

![CleanShot 2023-08-25 at 13 04 30@2x](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/76901736/ab04c55e-556e-48b0-90b5-e230086b010d)

How about just remove that column and rename these words to something keyword-related:

![CleanShot 2023-08-25 at 13 05 53@2x](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/76901736/1db6011e-c098-41aa-8c6f-af93d8ec8b2e)

2023-08-25 06:38 UTC, tednguyendev commented on src/app/(app)/searchResults/page.tsx
Maybe the folder name should be `search-results` instead of `searchResults`, as the convention of URLs is kebab case, not camel case:
<img width="136" alt="CleanShot 2023-08-25 at 13 11 02@2x" src="https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/76901736/51c75738-5aaa-4e9f-9bdd-7acfc99b816a">

2023-08-25 06:38 UTC, tednguyendev commented on src/components/Pagination/pagination.test.tsx
Should the file name be `Pagination.test.tsx` instead?

2023-08-25 06:38 UTC, tednguyendev commented on src/components/SearchResultList/SearchResultList.test.tsx
> +describe('Lists The Search Result', () => {
Why every words of this is capitalized 🙈

2023-08-25 06:38 UTC, tednguyendev commented on src/components/SearchResultList/SearchResultList.tsx
> +    (!loading && (
The table will looks better if we only show the loadings for [the body of the table](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/files#diff-082b2577a87e52b1266cce36139a4a71c7275509b6e8937ee29d9e93e35f22dcR88-R96) instead of the whole table(which also includes the table header):

![CleanShot 2023-08-25 at 13 22 55@2x](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/76901736/53c6aac6-47cd-4a60-89d6-6d1112465b42)

2023-08-25 06:38 UTC, tednguyendev commented on src/components/Pagination/pagination.test.tsx
> +  describe('given totalLength to be zero', () => {
```suggestion
  describe('given totalLength is zero', () => {
```

2023-08-25 06:38 UTC, tednguyendev commented on src/components/SearchResultList/SearchResultList.tsx
> +          }}
Will this still work? 👀 

```suggestion
          handleChange={setPageNumber}
```

2023-08-25 07:47 UTC, Prabeshpd commented on src/components/SearchResultList/SearchResultList.tsx
> +          }}
It is call back function. Meaning this number will be set from the pagination component to set the page number to query the database. It will not work.

2023-08-25 07:50 UTC, Prabeshpd commented on src/components/Pagination/pagination.test.tsx
> +  describe('given totalLength to be zero', () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/3991c309c8cb9ba2524c35bf86f731a67159e2a7

2023-08-25 07:50 UTC, Prabeshpd commented on src/app/(app)/searchResults/page.tsx
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/3991c309c8cb9ba2524c35bf86f731a67159e2a7

2023-08-25 07:50 UTC, Prabeshpd commented on src/components/SearchResultList/SearchResultList.tsx
> +              <th className="table__head-column">Position</th>
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/3991c309c8cb9ba2524c35bf86f731a67159e2a7

2023-08-25 07:54 UTC, Prabeshpd commented on src/components/SearchResultList/SearchResultList.tsx
> +    (!loading && (
Resolved in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/0a393030283c7105bbeb0d1047d5642689ceffdf

2023-08-25 08:35 UTC, tednguyendev commented on src/components/SearchResultList/SearchResultList.tsx
> +          }}
🤔 I still don't quite understand yet. I tried to run some tests on my local using both versions and it still work 🙈

2023-08-25 08:44 UTC, Prabeshpd commented on src/components/SearchResultList/SearchResultList.tsx
> +          }}
In this particular case. In the searchResult page the function on handleChange has no access to number of the page. So, a callback function is passed as a parameter to function. So, where the function is getting called they will pass the parameter. This is similar to the concept of withAuth that you have done in [With Auth for server actions](https://github.com/nimblehq/js-framework-benchmark/blob/develop/nextjs-13/src/lib/withAuth/withAuth.ts)

2023-08-25 08:46 UTC, tednguyendev commented on src/components/SearchResultList/SearchResultList.tsx
> +              <th className="table__head-column">Position</th>
It looks better now! Please also update the demo video 📷

2023-08-25 09:01 UTC, tednguyendev approved these changes

2023-08-29 04:12 UTC, olivierobert requested changes
Th implementation is cryptic and hard to read. You need to revisit the whole implementation while making sure you incorporate previous improvements for code style.

2023-08-29 04:12 UTC, olivierobert commented on src/components/SearchResultList/SearchResultList.tsx
> +      <div className="list-search-result__header">
How about using the `header` tag? If yes, then the whole parent can be changed to `section` instead of ` div`.

2023-08-29 04:12 UTC, olivierobert commented on src/hooks/debounce.ts
> +  useEffect(() => {
It feels off to me to use React state for that purpose. Debouncing can work without it. While it would mean to add a dependency, there is no need to reinvent wheel and use instead https://www.geeksforgeeks.org/lodash-_-debounce-method/

2023-08-29 04:12 UTC, olivierobert commented on src/stylesheets/base/_pagination.scss
> +    background-color: #1f2937;
Again an hard-coded color 🙈

2023-08-29 04:12 UTC, olivierobert commented on src/stylesheets/base/_table.scss
> +  &__head-column {
1. A table is composed of cells
2. Instead of using the parent element as a prefix, prefer using the CSS child selector

```suggestion
  &__head > &__cell {
```

2023-08-29 04:12 UTC, olivierobert commented on src/components/SearchResultList/SearchResultList.tsx
> +        <label htmlFor="table-search" className="sr-only">
Always warp labels and input elements in a form. It is not only semantically correct, but it allows to use form events and get free stuff such as URL updates on GET action.

2023-08-29 04:12 UTC, olivierobert commented on src/components/SearchResultList/SearchResultList.tsx
> +  const [value, setValue] = React.useState<string>('');
How about:

```suggestion
  const [goToPage, setGoToPage] = React.useState<string>('');
```

2023-08-29 04:12 UTC, olivierobert commented on src/components/SearchResultList/SearchResultList.test.tsx
> +      });
Is there a specific need to have 5 rows or is it arbitrary? Can't we do the same with one or two rows? Only use the required data that are really required for the test.

2023-08-30 02:26 UTC, Prabeshpd commented on src/app/(app)/search-results/page.tsx
> +        <h2>Search Result Table</h2>
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/39491e1a89fac370cec627939a65aea42323f570

2023-08-30 02:26 UTC, Prabeshpd commented on src/components/Pagination/hooks.ts
> +  pageNo: number;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/39491e1a89fac370cec627939a65aea42323f570

2023-08-30 02:26 UTC, Prabeshpd commented on src/components/Pagination/hooks.ts
> +  totalLength: number;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/39491e1a89fac370cec627939a65aea42323f570

2023-08-30 02:26 UTC, Prabeshpd commented on src/components/Pagination/hooks.ts
> +  NEXT = 'NEXT',
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/39491e1a89fac370cec627939a65aea42323f570

2023-08-30 02:27 UTC, Prabeshpd commented on src/components/Pagination/hooks.ts
> +function usePageTransfer(pageProps: PageProps) {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/39491e1a89fac370cec627939a65aea42323f570

2023-08-30 02:27 UTC, Prabeshpd commented on src/components/Pagination/hooks.ts
> +export interface PageProps {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/39491e1a89fac370cec627939a65aea42323f570

2023-08-30 02:27 UTC, Prabeshpd commented on src/components/Pagination/Pagination.tsx
> +  if (pageProps.totalPageNumber > 1) paginationChildren.push(nextLi);
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/39491e1a89fac370cec627939a65aea42323f570

2023-08-30 02:28 UTC, Prabeshpd commented on src/hooks/debounce.ts
> +  useEffect(() => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/b2c46eed6269f1b83b56d75234deb4aa4442f7bb

2023-08-30 02:28 UTC, Prabeshpd commented on src/components/SearchResultList/SearchResultList.tsx
> +  const [value, setValue] = React.useState<string>('');
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/b2c46eed6269f1b83b56d75234deb4aa4442f7bb

2023-08-30 02:28 UTC, Prabeshpd commented on src/components/SearchResultList/SearchResultList.test.tsx
> +      });
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/b2c46eed6269f1b83b56d75234deb4aa4442f7bb

2023-08-30 02:29 UTC, Prabeshpd commented on src/stylesheets/base/_table.scss
> +  &__head-column {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/99495156361e47333ffdabf8c07380429a2c5948

2023-08-30 03:37 UTC, olivierobert reviewed
Almost there 💦 Just a few minor changes and it will be ready to go

2023-08-30 03:37 UTC, olivierobert commented on src/components/Pagination/hooks.ts
> +  handleChange: (page: number) => void;
That comment is still valid as the props could be improved if declared as the following:

```typescript
export interface PaginationProps {
  perPageLimit: number;
  currentPage: number;
  totalRowCount: number;
  totalPageCount: number;

  handleChange: (page: number) => void;
}
```

2023-08-30 03:37 UTC, olivierobert commented on src/components/SearchResultList/SearchResultList.tsx
> +import _ from 'lodash';
Since the usage of `lodash` is limited to debounce, we can also only use https://www.npmjs.com/package/lodash.debounce and then use it as the following:

```
import debounce from 'lodash/debounce';
```

2023-08-30 03:37 UTC, olivierobert commented on src/app/(app)/search-results/page.tsx
> +      <div>
This div does not seem needed as there are no class associated to it and h2 is already a block element so it could be removed:

```suggestion
      
```

2023-08-30 03:37 UTC, olivierobert commented on src/components/Pagination/Pagination.tsx
> +    <nav className="pagination" data-testid="pagination">
Avoid single-word class names: https://nimblehq.co/compass/development/code-conventions/css/#convention-24

```suggestion
    <nav className="pagination-navigation" data-testid="pagination">
```

2023-08-30 03:37 UTC, olivierobert commented on src/components/Pagination/Pagination.tsx
> +        {RenderPaginationBlock({
How about returning the `ul` from that method to keep ul + li together and renaming it to:

```suggestion
        {PaginationList({
```

My previous comment on adding `render` was based on returning children elements but here it uses a whole component.

2023-08-30 03:51 UTC, Prabeshpd commented on src/app/(app)/search-results/page.tsx
> +      <div>
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/c90eb7025639f4a489f317ab727eab34e47c8589

2023-08-30 03:51 UTC, Prabeshpd commented on src/components/Pagination/Pagination.tsx
> +        {RenderPaginationBlock({
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/c90eb7025639f4a489f317ab727eab34e47c8589

2023-08-30 03:52 UTC, Prabeshpd commented on src/components/Pagination/Pagination.tsx
> +    <nav className="pagination" data-testid="pagination">
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/81/commits/9b7290de2b75163d97dca3a841796a4a5e735c95

2023-08-30 10:30 UTC, olivierobert approved these changes

2023-08-30 10:55 UTC, merged