[#18] [Backend] As a user, I can sign up with google
nimblehq/ic-nextjs-prabesh-dahal pull request #84
Opened 2023-08-28 10:49 UTC by Prabeshpd

- Close #18

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-30 04:06 UTC, olivierobert requested changes

2023-08-30 04:06 UTC, olivierobert commented on prisma/migrations/20230828090447_identities/migration.sql
> +    "is_active" BOOLEAN NOT NULL DEFAULT false,
That flag does not seem used, hence could be removed

2023-08-30 04:06 UTC, olivierobert commented on src/config/auth.ts
> +        return true;
When does this case happens. I am confused 🤔

2023-08-30 04:06 UTC, olivierobert commented on src/config/auth.ts
> +      return !!user;
Avoud double negatives (https://dev.to/mcsee/code-smell-51-double-negatives-4fh0) as it is harder to comprehend and makes sense of It.

2023-08-30 04:06 UTC, olivierobert commented on test/repositories/identity.test.ts
> +describe('identity:', () => {
Naming issue:

```suggestion
describe('Identity Repository', () => {
```

2023-08-30 04:06 UTC, olivierobert commented on test/repositories/identity.test.ts
> +  describe('creates identity', () => {
Ditto as it should be the method name:

```suggestion
  describe('createIdentity', () => {
```

2023-08-30 04:06 UTC, olivierobert commented on test/repositories/identity.test.ts
> +      describe('given identity does not relates to user', () => {
English syntax issue + tip to emphasize the sad path:

```suggestion
      describe('given identity does NOT relate to user', () => {
```

2023-08-30 04:06 UTC, olivierobert commented on test/repositories/identity.test.ts
> +    describe('given identity is not present', () => {
Minor reprhasing suggestion:

```suggestion
    describe('given identity does NOT exist', () => {
```

2023-08-30 04:28 UTC, Prabeshpd commented on src/config/auth.ts
> +        return true;
Sign in callback can activate for credentials too. So, I am returning it for the one where the provider is not google.

2023-08-30 06:55 UTC, Prabeshpd commented on test/repositories/identity.test.ts
> +    describe('given identity is not present', () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/84/commits/6b76e5248d44da9120517afdfbf615d3d1043d42

2023-08-30 06:56 UTC, Prabeshpd commented on src/config/auth.ts
> +      return !!user;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/84/commits/b90149544a7d35d98bfcb61fc30b6e34b93625fb

2023-08-30 06:56 UTC, Prabeshpd commented on src/services/auth.ts
> +export async function authenticateGoogleLogin(profile: Profile) {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/84/commits/b90149544a7d35d98bfcb61fc30b6e34b93625fb

2023-08-30 07:12 UTC, tednguyendev commented on src/services/auth.ts
> +    return user;
Will it still work if we remove this line? ✋

2023-08-30 08:19 UTC, Prabeshpd commented on test/services/user.test.ts
As discussed in previous project I was trying to disintegrate the test of database using the real database instance. So, for those test I would require not to use mock database created.For this I had been using two config for jest to use what instance of database. A separate ticket has been created to address this issue. I am planning to have only the test which interact with database.

2023-08-30 08:27 UTC, Prabeshpd commented on src/services/auth.ts
> +    return user;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/84/commits/a9503b46947a434b871ec4651acd06e2462210fd

2023-08-30 08:30 UTC, Prabeshpd commented on src/services/user.ts
> +      code: httpStatusCode.BAD_REQUEST,
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/84/commits/a9503b46947a434b871ec4651acd06e2462210fd

2023-08-30 09:02 UTC, tednguyendev commented on prisma/schema.prisma
> +  provider     String                   @db.VarChar(100)
Yes I don't mean to duplicate the enum.

What I mean is:

```suggestion
  provider     AuthProviders            @db.VarChar(100)
```

Can we use it like that 🤔 

Seems like Prisma Enum work with [key-value enum](https://stackoverflow.com/a/73569487) too

2023-08-30 09:17 UTC, Prabeshpd commented on prisma/schema.prisma
> +  provider     String                   @db.VarChar(100)
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/84/commits/8bf512a327a61e1d21c423084e0d6e1239d9a484

2023-08-30 10:09 UTC, tednguyendev commented on prisma/schema.prisma
> +  provider     String                   @db.VarChar(100)
But wait, with your implementation above, it will duplicate the enum? So Prisma not support us DRY this?

2023-08-30 10:28 UTC, tednguyendev commented on src/config/auth.ts
> +      return Boolean(user);
I still don't understand why the function `authenticateGoogleLogin` needs to return the `user` instead of just a boolean to indicate whether the authentication is successful or not.

2023-08-30 10:28 UTC, tednguyendev commented on src/services/user/user.ts
> +  return dbClient.$transaction(async (trx) => {
What `trx` stands for? We should prefer using meaningful names instead of short variable names.

2023-08-30 10:28 UTC, tednguyendev commented on src/repositories/identity.ts
> +  trx?: Prisma.TransactionClient
Why should we add this `trx` to the functions that not need to be executed in a transaction?

2023-08-30 10:28 UTC, tednguyendev commented on src/repositories/helper.ts
> +export const queryBuilder = (trx?: Prisma.TransactionClient) => trx || dbClient;
I don't think this function actually "builds" anything, right? 😆

2023-08-30 10:28 UTC, tednguyendev commented on test/repository/identity.test.ts
> +  describe('find identity', () => {
```suggestion
  describe('findByProvider', () => {
```

As you are using this format above

2023-08-30 10:28 UTC, tednguyendev commented on test/services/auth.test.ts
> +      it('throws custom error.', async () => {
```suggestion
      it('throws custom error', async () => {
```

2023-08-30 10:28 UTC, tednguyendev commented on test/services/auth.test.ts
> +    describe('when there is no user as credential', () => {
```suggestion
    describe('given there is no user as credential', () => {
```

As you are using `given` many places

2023-08-30 10:41 UTC, Prabeshpd commented on src/services/user/user.ts
> +  return dbClient.$transaction(async (trx) => {
will change it to transaction

2023-08-30 10:43 UTC, Prabeshpd commented on src/config/auth.ts
> +      return Boolean(user);
So, must of our authenticate function normally returns user. I think it doesnot makes sense to return boolean for user authentication for the next-auth scenario. It's in service layer and can be used on other scenarios as well. For consistency I am returning the user.

2023-08-30 10:54 UTC, Prabeshpd commented on src/repositories/helper.ts
> +export const queryBuilder = (trx?: Prisma.TransactionClient) => trx || dbClient;
renamed function name

2023-08-30 11:01 UTC, Prabeshpd commented on prisma/schema.prisma
> +  provider     String                   @db.VarChar(100)
It seems the prisma does allow to use it in code. I have updated the PR.

2023-08-31 02:45 UTC, tednguyendev commented on src/config/auth.ts
> +      return Boolean(user);
I see.

But what are the scenarios that this service will also be used? 🤔

2023-08-31 02:47 UTC, tednguyendev commented on src/repositories/identity.ts
> +  trx?: Prisma.TransactionClient
Thanks for your explanation.

Yes, if there are any functions that need to be used in a transaction, we can just add this additional param to them later 😄

2023-08-31 03:06 UTC, Prabeshpd commented on src/config/auth.ts
> +      return Boolean(user);
Since, We are building API for OAUTH. Although there is a API from next-auth but I think it is little complicate to extract token by clients we may want to expose the API for mobile devices separately. So, I was thinking to make separate API. But if we do not use this approach too. I think it is not good to return boolean from the authenticate function. I may be thinking too much. 😅 . I think we can create a separate function `hasAuthenticatedGoogleLogin` for boolean. Do you think is it a good idea? to define separate function

2023-08-31 03:45 UTC, tednguyendev commented on src/config/auth.ts
> +      return Boolean(user);
Ohh I see.

Yes, then maybe we can just leave it as `authenticateGoogleLogin` for now. We can comeback to this later.

2023-08-31 06:30 UTC, tednguyendev approved these changes

2023-09-04 03:38 UTC, olivierobert requested changes

2023-09-04 03:38 UTC, olivierobert commented on src/services/user/user.ts
> +export async function mergeExitingUser(user: User, authProvider: AuthProviders) {
Typo:

```suggestion
export async function mergeExistingUser(user: User, authProvider: AuthProviders) {
```

2023-09-04 03:38 UTC, olivierobert commented on src/config/auth.ts
> +        return true;
It would be best to then have a method lie the following:

```
if (isAuthCredentialFlow(account?.provider)) {
        return true;
}
```

Such code is self-documenting and it helps to understand what is going on 💡

2023-09-04 03:38 UTC, olivierobert commented on src/services/auth/auth.ts
> +export async function authenticateLogin(credentials: Credentials) {
The method name is hard to differentiate (especially when checking the tests). How about using the word `credential` as `Google` is used in the second method:

```suggestion
export async function authenticateCredentialLogin(credentials: Credentials) {
```

2023-09-04 03:38 UTC, olivierobert commented on test/services/auth.test.ts
> +  describe('Authenticate credential login', () => {
Inconsistency with the other tests. Prefer to use the method name:

```suggestion
  describe('authenticateLogin', () => {
```

2023-09-04 03:38 UTC, olivierobert commented on test/services/auth.test.ts
> +        const profile = { email: userEmail, name: 'dev nimble' };
As raised previously a test should follow the AAA pattern. So let's add a line break here after the Arrange block:

```suggestion
        const profile = { email: userEmail, name: 'dev nimble' };
        
```

Then the act block should be (one line):

```js
await authenticateGoogleLogin(profile);
```

Finally, the Assert block is:

```js
const authenticateUser = (await userRepository.findByEmail(userEmail)) as User;
const [identity] = await identityRepository.findByProvider(
  AuthProviders.google,
  authenticateUser.id
);

expect(identity).not.toBeNull();
expect(authenticateUser.email).toEqual(userEmail);
```

You need to recheck all tests added in this PR.

2023-09-04 04:08 UTC, Prabeshpd commented on test/services/auth.test.ts
> +        const profile = { email: userEmail, name: 'dev nimble' };
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/84/commits/f3a388edb96ff807b910abc71110e3dcca753c4b

2023-09-04 06:24 UTC, Prabeshpd commented on test/services/auth.test.ts
> +  describe('Authenticate credential login', () => {
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/84/commits/f3a388edb96ff807b910abc71110e3dcca753c4b

2023-09-04 08:42 UTC, olivierobert approved these changes

2023-09-04 08:43 UTC, merged