[#90] [API] As a user, I can view the list of search results
nimblehq/ic-nextjs-prabesh-dahal pull request #93
Opened 2023-08-30 15:58 UTC by Prabeshpd

- Close #90 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-31 08:52 UTC, tednguyendev commented on src/app/api/v1/searchResults/route.ts
> +    const totalRowCount = (await listSearchResult({ customQuery }, { isPaginated: false })).length;
This looks duplicated with the [searchResult.ts action](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/blob/b45084acb3244d9e6fe9894f6195109cd871aa82/src/app/actions/searchResult.ts#L14-L21).

2023-08-31 08:52 UTC, tednguyendev commented on test/api/searchResult.test.ts
> +describe('search result Get API:', () => {
Should this be

```suggestion
describe('Search result get API:', () => {
```

As you are using [that format](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/blob/3fdabf9f5438a15d6eb9e466d0f1fafde1f18e95/test/api/user.test.ts#L9) 🧓

2023-08-31 08:52 UTC, tednguyendev commented on src/presenters/searchResult.ts
> +  return { searchResults: data, meta };
If our presenter does not do any transformations, I wonder if we need it.

This is not something that pollutes the controller 😆

2023-08-31 09:10 UTC, Prabeshpd commented on src/app/api/v1/searchResults/route.ts
> +    const totalRowCount = (await listSearchResult({ customQuery }, { isPaginated: false })).length;
Yes, As the one in action is for the server actions. It will have its own authentication function. So, these two lines are repeated in API

2023-08-31 09:11 UTC, Prabeshpd commented on src/presenters/searchResult.ts
> +  return { searchResults: data, meta };
For, now I am not doing anything but to present in table I am thinking to have the map to format the data a little. I will have a ticket on next sprint to add columns in table.

2023-08-31 10:47 UTC, tednguyendev commented on src/app/api/v1/searchResults/route.ts
> +    const totalRowCount = (await listSearchResult({ customQuery }, { isPaginated: false })).length;
As the query will change, maybe we can skip it for now 🙏

2023-08-31 10:50 UTC, tednguyendev commented on src/presenters/searchResult.ts
> +  return { searchResults: data, meta };
Since you already added it, just leave it there 👍 

But I think we should not have the "preparation" code like this too much, since although they are harmless, they may cause some confusion for the reviewers(like me 🙈 )

2023-09-04 04:07 UTC, olivierobert commented on test/api/searchResult.test.ts
> +          id: 'cb77e671-2447-4197-897d-540bc114df48',
Since there is no assertion on the ID, can't this be removed and instead rely on the factory? It adds noise to the test for no benefit.

2023-09-04 04:07 UTC, olivierobert commented on test/api/searchResult.test.ts
> +import { searchResult } from '../factories/searchResult';
Let's be more descriptive as I wondered where `searchResult` came from when reading the code below:

```suggestion
import { searchResultFactory } from '../factories/searchResult';
```

2023-09-04 04:07 UTC, olivierobert commented on test/api/searchResult.test.ts
> +  describe('given pagination and filter params', () => {
Tehnically, this test does not add value as it is the same as the other test. To make this test more useful, we would need to test to catch with different pagination pages (e.g., currentPage = 2)

2023-09-04 04:11 UTC, olivierobert requested changes

2023-09-04 04:11 UTC, olivierobert commented on src/app/api/v1/searchResults/route.ts
URLs must be hyphenated, no camel-cased:

```
src/app/api/v1/search-results/route.ts
```

2023-09-04 04:11 UTC, olivierobert commented on test/api/searchResult.test.ts
> +describe('Search result get API:', () => {
Keep it simple with:

```suggestion
describe('GET api/v1/search-results', () => {
```

2023-09-04 04:41 UTC, Prabeshpd commented on test/api/searchResult.test.ts
> +import { searchResult } from '../factories/searchResult';
Since, if I change this naming I have to change in all of the files that use it. Would it be good if I do this in the task where I move all the tests to one directory.

2023-09-04 04:51 UTC, Prabeshpd commented on test/api/searchResult.test.ts
> +          id: 'cb77e671-2447-4197-897d-540bc114df48',
Since, the searchResult is an object in the factory file. It creates a single ID as UUID. If we try to insert multiple searchResults with same UUID we can not as it is a unique field.

2023-09-04 05:01 UTC, Prabeshpd commented on test/api/searchResult.test.ts
> +        url: `http://localhost:3000/api/v1/searchResults?currentPage=1&maxRows=10&userId=${createdUser.id}`,
No, It is not possible. As per my knowledge and research I did Next Request does not have the native query object. The code have to extract the query params from the url. Due to this we can not add the query object and add the params in the api url itself.

2023-09-05 03:51 UTC, olivierobert commented on test/api/searchResult.test.ts
> +        url: `http://localhost:3000/api/v1/searchResults?currentPage=1&maxRows=10&userId=${createdUser.id}`,
I did not test it but I found many examples showing support for `query`:

Example 1: https://seanconnolly.dev/unit-testing-nextjs-api-routes

<img width="828" alt="image" src="https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/696529/bd2adb33-4c18-4371-b06d-ed7ea2690c74">

Example 2: https://www.paigeniedringhaus.com/blog/how-to-unit-test-next-js-api-routes-with-typescript

<img width="823" alt="image" src="https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/696529/60c4a388-1e2a-41a8-b88e-0a9806bfe867">

In all examples, I noticed that it was to set the value for the path of the URL e.g., `'/api/[animal]'`. So which issue did you face?

Also, is it necessary to set the host and port? Can't `localhost:3000` be removed?

2023-09-05 03:54 UTC, olivierobert commented on test/api/searchResult.test.ts
> +import { searchResult } from '../factories/searchResult';
Understood. Then ensure you keep track of these changes to make.

2023-09-05 03:54 UTC, olivierobert commented on test/api/searchResult.test.ts
> +          id: 'cb77e671-2447-4197-897d-540bc114df48',
But isn't the point of using Faker to generate random UUID? 🤔 Having to define it by hand in each test seems to defeat the point of having a factory.

https://github.com/nimblehq/ic-nextjs-prabesh-dahal/blob/73ae713239079f3716a5427df9f59da853aa99fb/test/factories/searchResult.ts#L5

2023-09-05 03:57 UTC, Prabeshpd commented on test/api/searchResult.test.ts
> +        url: `http://localhost:3000/api/v1/searchResults?currentPage=1&maxRows=10&userId=${createdUser.id}`,
I tried it but the next Request is not taking the query. I think it's for next-12. I will give it a try once more. May be I had missed anything.

2023-09-05 03:58 UTC, Prabeshpd commented on test/api/searchResult.test.ts
> +          id: 'cb77e671-2447-4197-897d-540bc114df48',
Since, it is a object. The import instance has the object instance defined once. One thing we can do is call ```faker.string.uuid()``` in every object assign operator. I will do that.

2023-09-05 05:33 UTC, tednguyendev commented on src/app/api/v1/search-results/route.ts
> +    const userId = Number(url.searchParams.get('userId') || 1);
We will also remove this in this PR?

2023-09-05 06:00 UTC, Prabeshpd commented on src/app/api/v1/search-results/route.ts
> +    const userId = Number(url.searchParams.get('userId') || 1);
I don't think. Since it is a separate implementation for api authentication. It's safe to remove them on the separate PR. cc @olivierobert

2023-09-05 06:19 UTC, Prabeshpd commented on test/api/searchResult.test.ts
> +        url: `http://localhost:3000/api/v1/searchResults?currentPage=1&maxRows=10&userId=${createdUser.id}`,
Here is the[Link](https://dev.to/bikrantjung/how-to-access-url-params-in-incoming-request-nextjs-134-route-handlers-2887). I believe the nextjs 13 does not have the req.query context. So, we need to take the params for url. We cannot remove the host and port as we are converting the url from the request to URL object which will not be valid.

2023-09-05 06:36 UTC, Prabeshpd commented on test/api/searchResult.test.ts
> +          id: 'cb77e671-2447-4197-897d-540bc114df48',
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/93/commits/2b5e36f1c38ef3094d28d911e9b96c32a94d9266

2023-09-05 09:36 UTC, tednguyendev commented on test/api/searchResult.test.ts
> +        url: `http://localhost:3000/api/v1/searchResults?currentPage=1&maxRows=10&userId=${createdUser.id}`,
Ditto [this](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/94#discussion_r1315554299). And other places in this test too 👍

2023-09-06 04:16 UTC, olivierobert commented on test/api/searchResult.test.ts
> +        url: `http://localhost:3000/api/v1/searchResults?currentPage=1&maxRows=10&userId=${createdUser.id}`,
Then let's file it under a known issue of Next.JS 13. In that case, I recommend defining a constant or an env variable (used only in the test environment) to store `http://localhost:3000` so the test looks like:

```js
url: `http://${TEST_APP_HOST}/api/v1/searchResults?currentPage=1&maxRows=10&userId=${createdUser.id}`
```

It would allow not to duplicate this code, allows to change based on the environment but also add a comment where the contact or env is configured to document why this is needed:

```
// Request  in Next.JS > 13 does not support the query attribute, hence requires a fully qualified URL
TEST_APP_HOST="http://localhost:3000"
```

The implementation should be self-documenting the decisions made so that others will not have to figure out again the same challenges.

2023-09-06 04:33 UTC, olivierobert approved these changes

2023-09-06 04:33 UTC, Prabeshpd commented on test/api/searchResult.test.ts
> +        url: `http://localhost:3000/api/v1/searchResults?currentPage=1&maxRows=10&userId=${createdUser.id}`,
Have added the constant in env variable

2023-09-06 04:45 UTC, tednguyendev approved these changes

2023-09-06 04:46 UTC, merged