[#91] [API] As a user, I can view the detail of single keyword
nimblehq/ic-nextjs-prabesh-dahal pull request #94
Opened 2023-08-31 01:05 UTC by Prabeshpd

- Close #91 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-09-04 04:12 UTC, olivierobert requested changes

2023-09-04 04:12 UTC, olivierobert commented on test/api/searchResult[id].test.ts
> +describe('Search result get/[id] API:', () => {
Keep it simple with:

```suggestion
describe('GET api/v1/search-results/[id]', () => {
```

2023-09-04 04:12 UTC, olivierobert commented on test/api/searchResult[id].test.ts
> +  const defaultUUID = 'cb77e671-2447-4197-897d-540bc114df48';
As raised in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/93#discussion_r1314416253, I am unsure why this is needed at all

2023-09-04 06:21 UTC, Prabeshpd commented on test/api/searchResult[id].test.ts
> +  const defaultUUID = 'cb77e671-2447-4197-897d-540bc114df48';
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/94/commits/da168cecffdfdc1611bf799ff9789adca2786b10

2023-09-05 03:55 UTC, olivierobert requested changes

2023-09-05 03:55 UTC, olivierobert commented on test/api/searchResult[id].test.ts
> +          url: `http://localhost:3000/api/v1/searchResults?userId=${createdUser.id}`,
Still waiting on a resolution for https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/93#discussion_r1314413993

2023-09-05 05:29 UTC, tednguyendev commented on src/app/api/v1/search-results/[id]/route.ts
> +    const userId = Number(url.searchParams.get('userId') || 1);
You will remove this in this PR, too, right?

Friendly reminder: remember to also update the demo ✋

![CleanShot 2023-09-05 at 12 28 42@2x](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/assets/76901736/32c63892-00dc-48ce-958c-ce2a351b639b)

2023-09-05 05:56 UTC, Prabeshpd commented on src/app/api/v1/search-results/[id]/route.ts
> +    const userId = Number(url.searchParams.get('userId') || 1);
No. As this is done through the api authentication. It has a separate tasks. I think it's safe to remove on the api authentication task. cc @olivierobert

2023-09-05 06:36 UTC, tednguyendev commented on src/app/api/v1/search-results/[id]/route.ts
> +    const userId = Number(url.searchParams.get('userId') || 1);
Ah I see. Thank you!

2023-09-05 06:52 UTC, tednguyendev commented on test/api/searchResult[id].test.ts
> +describe('GET api/v1/search-results/[id]:', () => {
Instead of:

```js
describe('GET api/v1/search-results/[id]:', () => {
  describe('given valid id', () => {
    describe('given user has search result', () => {
      it('returns valid data', async () => {
      });

      describe('given user has NO given search result', () => {
        it('rejects with unprocessable entity error', async () => {
        });
      });
    });
  });

  describe('given INVALID id', () => {
    it('rejects with unprocessable entity error', async () => {
    });
  });
});
```

How about just:

```js
describe('GET api/v1/search-results/[id]:', () => {
  describe('given user has search result', () => {
    it('returns valid data', async () => {
    });
  });

  describe('given user has NO given search result', () => {
    it('rejects with unprocessable entity error', async () => {
    });
  });
});
```

As I don't understand what it means for the ID to be valid or not. Our `findById` just cares about whether it can query a record or not.

2023-09-05 08:26 UTC, tednguyendev commented on test/api/searchResult[id].test.ts
> +        url: `http://localhost:3000/api/v1/searchResults?userId=${createdUser.id}`,
```suggestion
        url: `http://localhost:3000/api/v1/search-results?userId=${createdUser.id}`,
```

2023-09-05 09:40 UTC, tednguyendev approved these changes

2023-09-06 04:38 UTC, Prabeshpd commented on test/api/searchResult[id].test.ts
> +          url: `http://localhost:3000/api/v1/searchResults?userId=${createdUser.id}`,
Resolved in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/94/commits/4edc3d0d7cdec2786123aa4882efe9dcbcc9282d

2023-09-06 04:45 UTC, olivierobert approved these changes

2023-09-06 04:46 UTC, merged