[#96] [Chore] Create a query class to segregate filter logic
nimblehq/ic-nextjs-prabesh-dahal pull request #97
Opened 2023-09-01 07:46 UTC by Prabeshpd

- Close #96 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-09-05 06:53 UTC, Prabeshpd commented on src/repositories/searchResult.ts
> -      skip: paginationQuery?.offset || PAGINATION_OFFSET_ROWS,
It is removed code. We already have that in constants file.

2023-09-05 07:13 UTC, tednguyendev commented on src/repositories/searchResult.ts
> -      skip: paginationQuery?.offset || PAGINATION_OFFSET_ROWS,
Yes what I mean is that, since we don't use `PAGINATION_OFFSET_ROWS` in any places anymore, should we just remove it from the constant file 🙈

2023-09-05 07:25 UTC, Prabeshpd commented on src/queries/BaseQuery.ts
> +  databaseModal: any;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/97/commits/849092657f8f313583895222ba27cca44d540c0d

2023-09-05 07:25 UTC, Prabeshpd commented on src/repositories/searchResult.ts
> -      skip: paginationQuery?.offset || PAGINATION_OFFSET_ROWS,
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/97/commits/849092657f8f313583895222ba27cca44d540c0d

2023-09-05 08:48 UTC, tednguyendev commented on src/queries/SearchResultQuery.ts
> +    this.filterQuery = {};
Will this be redundant since we already defined it on [`BaseQuery`](https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/97/files#diff-a7d7eefdc532120d57f3857856af33ec17db04792816171ce0fd3892f2c4abe5R30)? 🙈

2023-09-05 08:48 UTC, tednguyendev commented on test/queries/baseQuery.test.ts
> +  describe('given pagination params', () => {
We can remove this `describe` ✋

2023-09-05 10:08 UTC, tednguyendev approved these changes
Look better now 👍

2023-09-07 03:27 UTC, olivierobert requested changes
One minor class restructuring and this is good to go

2023-09-07 03:27 UTC, olivierobert commented on src/queries/BaseQuery.ts
> +  async call() {
This is more idiomatic for Ruby code (it is related to lambda) but less so in a JS codebase. In addition, having two async methods `call1 and `query` seems redundant. Both could be merged together.

```suggestion
  async query() {
    this.buildPaginationQueryParams();
    
    return this.databaseModel.findMany({
      where: { ...this.filterQuery },
      ...this.paginationQuery,
    });
  }
```

2023-09-07 03:27 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +  async call() {
The same would apply here in merging both `call` and `query` methods

2023-09-07 04:32 UTC, olivierobert approved these changes

2023-09-07 04:42 UTC, merged