[#19] [Backend] As a user, I can search specific URL in the result
nimblehq/ic-nextjs-prabesh-dahal pull request #98
Opened 2023-09-01 08:26 UTC by Prabeshpd

- Close #19 

## What happened 👀

- Add a filter logic to search with specific url.
- Add test

## Insight 📝

Added filter logic to search for specific url. I have not combined the filter logic with keyword as it is kind of a different requirement. 
> [!Note] [PR](Change in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/95) is here for searching specific URL

## Proof Of Work 📹
Passing CI Pipelines

2023-09-04 04:18 UTC, olivierobert requested changes

2023-09-04 04:18 UTC, olivierobert commented on src/app/actions/searchResult.ts
> +// To Do create a interface for arguments greater than 3
Wrong expected casing:

```suggestion
// TOTO: create an interface for arguments greater than 3
```

At the same time, this comment is not that useful 😅

2023-09-04 04:18 UTC, olivierobert commented on src/queries/SearchResultQuery.ts
> +    if (!this.urlToFilter) return;
Lets add a line brak for readability

```suggestion
    if (!this.urlToFilter) return;
    
```

2023-09-04 04:18 UTC, olivierobert commented on src/app/actions/searchResult.ts
> +  urlToFilter?: string
How about grouping the related params together:

```
interface searchResultFilter {
  keyword?: string,
  url?: string
}

export async function listSearchResults(
  paginationParams: PaginationParams,
  filters: searchResultFilter 
}
```

The same applied to `SearchResultQuery` as it is best to limit the max number of params to 2-3 at most whenever possible.

2023-09-04 06:35 UTC, Prabeshpd commented on src/app/actions/searchResult.ts
> +  urlToFilter?: string
I have done this in the upcoming PR. For this I had added an TODO 😅. To group the params for params  greater than 3.

2023-09-04 06:39 UTC, Prabeshpd commented on src/queries/SearchResultQuery.ts
> +    if (!this.urlToFilter) return;
Fixed in https://github.com/nimblehq/ic-nextjs-prabesh-dahal/pull/98/commits/2044255a548e5647eac03294d316b890738984be

2023-09-05 04:15 UTC, olivierobert commented on src/app/actions/searchResult.ts
> +  urlToFilter?: string
I saw that PR, but it is getting hard to approve PRs with TODOs all the time. So since this PR is the first implementing the filters, bring the changes here.

2023-09-05 09:34 UTC, Prabeshpd commented on src/app/actions/searchResult.ts
> +  urlToFilter?: string
I have brought the changes from other PR. Can you have a look at it please?

2023-09-06 03:35 UTC, tednguyendev commented on test/queries/searchResultQuery.test.ts
> +    describe('given valid param for url filter', () => {
```suggestion
    describe('given there is url filter', () => {
```

2023-09-06 03:35 UTC, tednguyendev commented on test/queries/searchResultQuery.test.ts
> +    describe('there is NO filter url param', () => {
```suggestion
    describe('given there is NO url filter', () => {
```

2023-09-06 04:51 UTC, olivierobert approved these changes

2023-09-06 04:51 UTC, olivierobert commented on test/queries/searchResultQuery.test.ts
> +    describe('there is NO filter url param', () => {
@Prabeshpd get these solved before mergeing

2023-09-06 04:52 UTC, olivierobert commented on test/queries/searchResultQuery.test.ts
> +        await createManySearchResults(searchResultPayload);
Why creating it if we do not need it for the test?

2023-09-06 06:27 UTC, tednguyendev commented on test/queries/searchResultQuery.test.ts
> +    describe('given given there is url filter', () => {
🙈 

```suggestion
    describe('give there is url filter', () => {
```

2023-09-06 06:27 UTC, tednguyendev approved these changes

2023-09-07 04:42 UTC, merged